[package]
name = "soshal-search-core"
version = { workspace = true }
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
soshal-nostr-core = { path = "../nostr-core" }
soshal-content-core = { path = "../content-core" }
soshal-common-core = { path = "../common-core" }
rayon = { workspace = true }

[dev-dependencies]
soshal-test-util = { path = "../test-util" }

[lints]
workspace = true
