[package]
name = "soshal-social-core"
version = { workspace = true }
edition = "2021"

[dependencies]
soshal-common-core = { path = "../common-core" }
serde = { workspace = true }
serde_json = { workspace = true }
soshal-nostr-core = { path = "../nostr-core" }

[dev-dependencies]
soshal-test-util = { path = "../test-util" }

[lints]
workspace = true
