[package]
name = "soshal-groups-core"
version = { workspace = true }
edition = "2021"

[dependencies]
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
soshal-crypto-core = { path = "../crypto-core" }
soshal-nostr-core = { path = "../nostr-core" }
soshal-common-core = { path = "../common-core" }
zeroize = { workspace = true }
pbkdf2 = { workspace = true }
sha2 = { workspace = true }
getrandom = { workspace = true }

[lints]
workspace = true
