[package]
name = "soshal-nostr-core"
version = { workspace = true }
edition = "2021"

[dependencies]
nostr-sdk = { workspace = true }
nostr = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
soshal-content-core = { path = "../content-core" }
soshal-common-core = { path = "../common-core" }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
