[package]
name = "soshal-storage-core"
version = { workspace = true }
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
soshal-common-core = { path = "../common-core" }
hex = { workspace = true }
ring = { workspace = true }
zeroize = { workspace = true }
raptorq = "1.8"
libc = { workspace = true }
memmap2 = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7"



[lints]
workspace = true
