[package]
name = "soshal-media-core"
version = { workspace = true }
edition = "2021"

[dependencies]
base64 = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
fastcdc = { workspace = true }
blake3 = { workspace = true }
memmap2 = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "gif"] }
soshal-crypto-core = { path = "../crypto-core" }
soshal-pqc-core = { path = "../pqc-core" }
soshal-nostr-core = { path = "../nostr-core" }
soshal-common-core = { path = "../common-core" }
thumbhash.workspace = true
url.workspace = true
tokio = { version = "1", features = ["net", "macros", "rt-multi-thread"] }

[lints]
workspace = true

[dev-dependencies]
soshal-test-util = { path = "../test-util" }
