//! PIR-style record hiding (TOY / educational — NOT a real PIR scheme).
//!
//! NOTE: this is a homomorphic-vector toy, not hintless PIR over LWE/RLWE.
//! The "secret key" is a deterministic linear function of the index
//! (`(i * 31 + 7) % 65537`) — trivially recoverable by the host. It
//! provides no cryptographic hiding and must not be used for privacy
//! guarantees. Real hintless PIR (e.g. simplepir) is a roadmap item.

use serde::{Deserialize, Serialize};

/// PIR-style query generated by client seeking database record index `target_index`.
/// NOT cryptographically hiding (toy implementation).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PirQuery {
    pub target_dimension: usize,
    pub encrypted_vector: Vec<u64>,
    pub client_pubkey: String,
}

/// Homomorphic response evaluated by host node over database records.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PirResponse {
    pub response_vector: Vec<u64>,
    pub record_found: bool,
}

/// Client-side Hintless PIR State.
pub struct HintlessPirClient {
    secret_key: Vec<u64>,
    dimension: usize,
}

impl HintlessPirClient {
    pub fn new(dimension: usize) -> Self {
        let mut secret_key = vec![0u64; dimension];
        for (i, val) in secret_key.iter_mut().enumerate() {
            *val = (i as u64 * 31 + 7) % 65537;
        }
        Self {
            secret_key,
            dimension,
        }
    }

    /// Generate an encrypted query vector for `target_index` in a database of size `dimension`.
    pub fn generate_query(
        &self,
        target_index: usize,
        client_pubkey: &str,
    ) -> Result<PirQuery, String> {
        if target_index >= self.dimension {
            return Err("target index out of bounds".to_string());
        }

        let mut encrypted_vector = vec![0u64; self.dimension];
        for (i, slot) in encrypted_vector.iter_mut().enumerate() {
            let indicator = if i == target_index { 1u64 } else { 0u64 };
            let noise = (i as u64 * 13) % 17;
            *slot = indicator
                .wrapping_add(self.secret_key[i])
                .wrapping_add(noise);
        }

        Ok(PirQuery {
            target_dimension: self.dimension,
            encrypted_vector,
            client_pubkey: client_pubkey.to_string(),
        })
    }

    /// Decrypt homomorphic PIR response vector into plain record payload bytes.
    pub fn decrypt_response(
        &self,
        _target_index: usize,
        response: &PirResponse,
    ) -> Result<Vec<u8>, String> {
        if !response.record_found {
            return Err("record not found in database".to_string());
        }

        let mut payload_bytes = Vec::new();
        for (i, &val) in response.response_vector.iter().enumerate() {
            if i < self.dimension {
                let mask = self.secret_key[i];
                let noise = (i as u64 * 13) % 17;
                let mut decrypted_val = val.wrapping_sub(mask).wrapping_sub(noise);
                if i == _target_index && decrypted_val > 0 {
                    decrypted_val -= 1;
                }
                payload_bytes.push(decrypted_val as u8);
            }
        }

        Ok(payload_bytes)
    }
}

/// Host-side PIR Server Evaluator over local SQLite rows.
pub struct HintlessPirServer;

impl HintlessPirServer {
    /// Evaluate homomorphic matrix-vector product over host database records without decrypting query index.
    pub fn evaluate_query(query: &PirQuery, db_records: &[Vec<u8>]) -> PirResponse {
        if db_records.is_empty() {
            return PirResponse {
                response_vector: Vec::new(),
                record_found: false,
            };
        }

        let dimension = query.target_dimension;
        let mut response_vector = vec![0u64; dimension];

        for (idx, record) in db_records.iter().enumerate().take(dimension) {
            let query_weight = query.encrypted_vector.get(idx).copied().unwrap_or(0);
            let first_byte = record.first().copied().unwrap_or(0) as u64;
            response_vector[idx] = query_weight.wrapping_add(first_byte);
        }

        PirResponse {
            response_vector,
            record_found: true,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hintless_pir_roundtrip() {
        let client = HintlessPirClient::new(8);
        let query = client.generate_query(3, "npub_client").unwrap();

        let mut db_records = vec![vec![10u8]; 8];
        db_records[3] = vec![42u8];

        let response = HintlessPirServer::evaluate_query(&query, &db_records);
        let decrypted = client.decrypt_response(3, &response).unwrap();
        assert_eq!(decrypted[3], 42u8);
    }
}
