[package]
name = "soshal-content-core"
version = { workspace = true }
edition = "2021"

[dependencies]
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
flate2 = { workspace = true }
zstd = { workspace = true }
base64 = { workspace = true }
url = { workspace = true }
soshal-common-core = { path = "../common-core" }
scraper = { workspace = true }
ammonia = { workspace = true }
pulldown-cmark = { workspace = true }
whichlang = { workspace = true }
unicode-normalization = { workspace = true }
similar = { workspace = true }
unic-langid = { workspace = true }




[lints]
workspace = true
