[package]
name = "soshal-layout-core"
version = { workspace = true }
edition = "2021"

[dependencies]
rustybuzz = "0.18"
owned_ttf_parser = "0.25"
unicode-linebreak = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = "1.19"
rapier2d.workspace = true

[lints]
workspace = true
