[package]
name = "soshal-mesh-core"
version = { workspace = true }
edition = "2021"

[dependencies]
base64 = { workspace = true }
blake3 = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
ring = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

soshal-common-core = { path = "../common-core" }
soshal-content-core = { path = "../content-core" }
soshal-crypto-core = { path = "../crypto-core" }
soshal-media-core = { path = "../media-core" }
soshal-pqc-core = { path = "../pqc-core" }

tokio-rustls = "0.26"
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-webpki-roots"] }
tungstenite = "0.21"
webpki-roots = "0.26"

[lints]
workspace = true

[dev-dependencies]
soshal-test-util = { path = "../test-util" }
