// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String analyticsComputeStats() =>
    RustLib.instance.api.crateFfiAnalyticsAnalyticsComputeStats();

/// Generate dense vector embedding using hardware-accelerated Burn SLM engine.
String analyticsSlmGenerateEmbedding({required String text}) =>
    RustLib.instance.api
        .crateFfiAnalyticsAnalyticsSlmGenerateEmbedding(text: text);

/// Classify post text for sentiment & automated spam detection locally via Burn SLM.
String analyticsSlmClassifyPost({required String text}) =>
    RustLib.instance.api.crateFfiAnalyticsAnalyticsSlmClassifyPost(text: text);
