// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// True only on Android ≥ 26 (AAudio + AImage gate).
bool audioIsSupported() => RustLib.instance.api.crateFfiAudioAudioIsSupported();

/// Start mic + AAC-LC encoder + capture thread. Caller must
/// `audio_set_mic_enable(true)` before audio flows.
bool audioInitEncode() => RustLib.instance.api.crateFfiAudioAudioInitEncode();

/// Toggle the mic. Returns immediately; keep polling `audio_drain`.
bool audioSetMicEnable({required bool on_}) =>
    RustLib.instance.api.crateFfiAudioAudioSetMicEnable(on_: on_);

/// Drain queued AAC blobs: `[2, ...config]` or `[1, ...frame]`.
List<Uint8List> audioDrain() => RustLib.instance.api.crateFfiAudioAudioDrain();

/// Set up the AAC decoder + AAudio output. Safe to call once per viewer
/// session.
bool audioInitDecode() => RustLib.instance.api.crateFfiAudioAudioInitDecode();

/// Feed one AAC blob (config or frame); decoded PCM plays immediately.
bool audioFeedAac({required List<int> blob}) =>
    RustLib.instance.api.crateFfiAudioAudioFeedAac(blob: blob);

/// Stop mic, codecs, playback; release everything.
bool audioRelease() => RustLib.instance.api.crateFfiAudioAudioRelease();
