// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// List audit log rows, newest first. Returns JSON array of
/// `{id, group_id, actor_pubkey, action, target_pubkey, details, created_at}`.
String auditList({required PlatformInt64 limit, String? actorPubkey}) =>
    RustLib.instance.api
        .crateFfiAuditAuditList(limit: limit, actorPubkey: actorPubkey);
