// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Result wrapper for FFI operations.
///
/// Thin alias over `Result<T, String>` so flutter_rust_bridge maps errors to
/// Generate a new keypair and unlock the signer
String authGenerateKeypair() =>
    RustLib.instance.api.crateFfiAuthAuthGenerateKeypair();

/// Generate a new BIP-39 mnemonic phrase
String authGenerateMnemonic() =>
    RustLib.instance.api.crateFfiAuthAuthGenerateMnemonic();

/// Validate a BIP-39 mnemonic phrase
bool authValidateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateFfiAuthAuthValidateMnemonic(mnemonic: mnemonic);

/// Restore a keypair from a BIP-39 mnemonic and unlock the in-process signer
Future<String> authRestoreFromMnemonic(
        {required String mnemonic, required String passphrase}) =>
    RustLib.instance.api.crateFfiAuthAuthRestoreFromMnemonic(
        mnemonic: mnemonic, passphrase: passphrase);

/// Get public key from nsec (bech32 encoded secret key)
String authPublicKeyFromNsec({required String nsec}) =>
    RustLib.instance.api.crateFfiAuthAuthPublicKeyFromNsec(nsec: nsec);

/// Encode public key as npub (bech32)
String authNpubEncode({required String publicKey}) =>
    RustLib.instance.api.crateFfiAuthAuthNpubEncode(publicKey: publicKey);

/// Decode npub to hex public key
String authNpubDecode({required String npub}) =>
    RustLib.instance.api.crateFfiAuthAuthNpubDecode(npub: npub);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KeyPairResult>>
abstract class KeyPairResult implements RustOpaqueInterface {
  String get publicKey;

  ZeroizingString get secretKey;

  set publicKey(String publicKey);

  set secretKey(ZeroizingString secretKey);
}
