// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `publish_bookmark_list`

/// Save a bookmark for an event. Returns the bookmark id (event id).
String bookmarksSave({required String pubkey, required String eventId}) =>
    RustLib.instance.api
        .crateFfiBookmarksBookmarksSave(pubkey: pubkey, eventId: eventId);

/// List bookmarks for a pubkey, newest first. Returns JSON array of
/// `{id, pubkey, event_id, created_at}`.
String bookmarksList(
        {required String pubkey,
        required PlatformInt64 limit,
        required PlatformInt64 offset}) =>
    RustLib.instance.api.crateFfiBookmarksBookmarksList(
        pubkey: pubkey, limit: limit, offset: offset);

/// Delete a bookmark by id. Returns true if a row was removed.
bool bookmarksDelete({required String id}) =>
    RustLib.instance.api.crateFfiBookmarksBookmarksDelete(id: id);

/// Resolve a bookmarked event from the local DB cache.
/// Returns JSON of PostRow or empty string if not found.
String bookmarksResolvePost({required String eventId}) => RustLib.instance.api
    .crateFfiBookmarksBookmarksResolvePost(eventId: eventId);
