// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `signal_kind`

/// Send a call signal to `target_pubkey`. SDP and candidates are redacted of
/// private IP literals before relay publish. Returns the event id.
Future<String> callsSendSignal(
        {required String signalType,
        required String targetPubkey,
        required String callId,
        String? sdp,
        String? candidate,
        String? mediaType}) =>
    RustLib.instance.api.crateFfiCallsCallsSendSignal(
        signalType: signalType,
        targetPubkey: targetPubkey,
        callId: callId,
        sdp: sdp,
        candidate: candidate,
        mediaType: mediaType);

/// Fetch call signals addressed to me (kinds 20001-20004, `#p` tag filter).
/// Returns JSON array of `{id, pubkey, content, created_at, kind, p_tags,
/// call_id}` — only verified events, p-tag verified to `my_pubkey`.
Future<String> callsFetchSignals({required String myPubkey}) =>
    RustLib.instance.api.crateFfiCallsCallsFetchSignals(myPubkey: myPubkey);

/// Sanitize an SDP for the local media session.
String callsSanitizeSdp({required String sdp, required bool forceRelay}) =>
    RustLib.instance.api
        .crateFfiCallsCallsSanitizeSdp(sdp: sdp, forceRelay: forceRelay);

/// ICE configuration for the local peer connection.
String callsIceConfig(
        {required String privacyLevel, required String stunUrl}) =>
    RustLib.instance.api.crateFfiCallsCallsIceConfig(
        privacyLevel: privacyLevel, stunUrl: stunUrl);
