// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Build the availability content JSON for an announcement.
String chatrandomAvailableContent(
        {required List<String> interests,
        required String mediaType,
        required String mode}) =>
    RustLib.instance.api.crateFfiChatrandomChatrandomAvailableContent(
        interests: interests, mediaType: mediaType, mode: mode);

/// Sign + publish a chatrandom event for `request_type` (`request`/`accept`)
/// addressed to `peers` (p-tags). Returns the event id.
Future<String> chatrandomSend(
        {required String requestType,
        required List<String> peers,
        required String contentJson}) =>
    RustLib.instance.api.crateFfiChatrandomChatrandomSend(
        requestType: requestType, peers: peers, contentJson: contentJson);

/// Fetch chatrandom events (kinds 20030/20031/20032) addressed to me or by
/// `author`. Returns JSON array of peer entries.
Future<String> chatrandomFetch(
        {required String myPubkey, String? author, required BigInt limit}) =>
    RustLib.instance.api.crateFfiChatrandomChatrandomFetch(
        myPubkey: myPubkey, author: author, limit: limit);
