// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<String> contentExtractHashtags({required String text}) =>
    RustLib.instance.api.crateFfiContentContentExtractHashtags(text: text);

/// Compress JSON with the bundled zstd dictionary (feed payloads).
String contentCompressJsonDict({required String data}) =>
    RustLib.instance.api.crateFfiContentContentCompressJsonDict(data: data);

/// Decompress a zstd-dict payload; transparently falls back to deflate.
String contentDecompressJsonDict({required String encoded}) =>
    RustLib.instance.api
        .crateFfiContentContentDecompressJsonDict(encoded: encoded);

/// Parse a text blob leniently, capping nesting/depth; JSON in, JSON out.
String contentSafeJsonParse({required String text}) =>
    RustLib.instance.api.crateFfiContentContentSafeJsonParse(text: text);

/// Extract video URLs from an imeta-style tags JSON array (JSON out).
String contentExtractImetaVideoUrls({required String tagsJson}) =>
    RustLib.instance.api
        .crateFfiContentContentExtractImetaVideoUrls(tagsJson: tagsJson);
