// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Parse + strictly validate a custom profile (kind 30085) payload.
/// Returns canonical JSON or an error describing the violation.
String contentCustomProfileValidate({required String profileJson}) =>
    RustLib.instance.api
        .crateFfiContentContentCustomProfileValidate(profileJson: profileJson);

/// Default node JSON for a node type (schema authority moved out of Dart).
String contentCustomProfileDefaultNode(
        {required String nodeType, required BigInt index}) =>
    RustLib.instance.api.crateFfiContentContentCustomProfileDefaultNode(
        nodeType: nodeType, index: index);

/// The 12 supported node types as JSON: [{type,label,icon}].
String contentCustomProfileNodeTypes() =>
    RustLib.instance.api.crateFfiContentContentCustomProfileNodeTypes();

/// Empty default profile JSON: {"themeId":"default","nodes":[]}.
String contentCustomProfileDefaultProfile() =>
    RustLib.instance.api.crateFfiContentContentCustomProfileDefaultProfile();

/// Compress JSON with the bundled zstd dictionary (feed payloads).
String contentCompressJsonDict({required String data}) =>
    RustLib.instance.api.crateFfiContentContentCompressJsonDict(data: data);

/// Decompress a zstd-dict payload; transparently falls back to deflate.
String contentDecompressJsonDict({required String encoded}) =>
    RustLib.instance.api
        .crateFfiContentContentDecompressJsonDict(encoded: encoded);
