// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// SHA256 hash of a string; returns 64 hex chars.
String cryptoSha256Hex({required String input}) =>
    RustLib.instance.api.crateFfiCryptoCryptoSha256Hex(input: input);

/// SHA256 hash of raw bytes.
Uint8List cryptoSha256({required List<int> input}) =>
    RustLib.instance.api.crateFfiCryptoCryptoSha256(input: input);

/// HMAC-SHA256 over `message` with `key`.
Uint8List cryptoHmacSha256(
        {required List<int> key, required List<int> message}) =>
    RustLib.instance.api
        .crateFfiCryptoCryptoHmacSha256(key: key, message: message);

/// NIP-44 v2 encrypt to `recipient_pubkey` with the unlocked signer key.
/// Returns the wire-format base64 payload.
String cryptoNip44Encrypt(
        {required String plaintext, required String recipientPubkey}) =>
    RustLib.instance.api.crateFfiCryptoCryptoNip44Encrypt(
        plaintext: plaintext, recipientPubkey: recipientPubkey);

/// NIP-44 v2 decrypt a payload from `sender_pubkey` with the unlocked signer
/// key.
String cryptoNip44Decrypt(
        {required String payload, required String senderPubkey}) =>
    RustLib.instance.api.crateFfiCryptoCryptoNip44Decrypt(
        payload: payload, senderPubkey: senderPubkey);

/// PQC KEM: generate a hybrid (X25519 + ML-KEM-768) keypair.
/// PQC KEM: generate post-quantum hybrid keypair off the UI isolate.
/// Returns JSON `{"pk": "<hex>", "sk": "<hex>"}`.
Future<String> cryptoPqcKemKeygen() =>
    RustLib.instance.api.crateFfiCryptoCryptoPqcKemKeygen();

/// PQC KEM: encapsulate to a hybrid public key.
/// Returns JSON `{"ct": "<hex>", "ss": "<hex>"}`.
Future<String> cryptoPqcKemEncaps({required String recipientPk}) =>
    RustLib.instance.api
        .crateFfiCryptoCryptoPqcKemEncaps(recipientPk: recipientPk);

/// PQC KEM: decapsulate a hybrid ciphertext with the secret key.
/// Returns the 32-byte shared secret as hex.
Future<String> cryptoPqcKemDecaps(
        {required String ciphertext, required String sk}) =>
    RustLib.instance.api
        .crateFfiCryptoCryptoPqcKemDecaps(ciphertext: ciphertext, sk: sk);

/// HKDF-SHA256 key expansion (RFC 5869) with the given salt and info.
/// Returns `len` derived bytes as hex.
String cryptoHkdfExpand(
        {required List<int> ikm,
        required List<int> salt,
        required List<int> info,
        required BigInt len}) =>
    RustLib.instance.api.crateFfiCryptoCryptoHkdfExpand(
        ikm: ikm, salt: salt, info: info, len: len);

/// Zeroize helper: accepts a buffer and returns success; the Rust side uses
/// `zeroize` internally on key material (this keeps a destroy-by-pointer
/// hook for Dart-level sensitive buffers that wish to clear after use).
bool cryptoZeroize({required List<int> data}) =>
    RustLib.instance.api.crateFfiCryptoCryptoZeroize(data: data);

/// Generate `len` cryptographically secure random bytes, returned hex.
String cryptoRandomBytes({required int len}) =>
    RustLib.instance.api.crateFfiCryptoCryptoRandomBytes(len: len);

/// Hintless PIR: generate an encrypted query vector for database target index.
Future<String> cryptoPirGenerateQuery(
        {required BigInt targetIndex,
        required BigInt dimension,
        required String clientPubkey}) =>
    RustLib.instance.api.crateFfiCryptoCryptoPirGenerateQuery(
        targetIndex: targetIndex,
        dimension: dimension,
        clientPubkey: clientPubkey);

/// Hintless PIR: evaluate homomorphic query over host database record payload bytes.
Future<String> cryptoPirEvaluateQuery(
        {required String queryJson, required List<String> recordHexList}) =>
    RustLib.instance.api.crateFfiCryptoCryptoPirEvaluateQuery(
        queryJson: queryJson, recordHexList: recordHexList);

/// FROST: generate jury key shares for t-of-n community moderation.
Future<String> cryptoFrostGenerateJuryKeys(
        {required int threshold,
        required int totalParticipants,
        required String groupPubkey}) =>
    RustLib.instance.api.crateFfiCryptoCryptoFrostGenerateJuryKeys(
        threshold: threshold,
        totalParticipants: totalParticipants,
        groupPubkey: groupPubkey);

/// FROST: aggregate partial signature shares into a valid single Schnorr threshold signature.
Future<String> cryptoFrostAggregateSignature(
        {required String sharesJson,
        required int threshold,
        required String groupPubkey,
        required String messageHex}) =>
    RustLib.instance.api.crateFfiCryptoCryptoFrostAggregateSignature(
        sharesJson: sharesJson,
        threshold: threshold,
        groupPubkey: groupPubkey,
        messageHex: messageHex);
