// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `daemons_dir`, `files_dir`, `is_running`, `spawn`, `write_file`

/// Extract the three bundled daemons from assets into files/daemons/.
/// Returns false if extraction is unsupported (no bundled assets).
bool daemonExtractDaemons() =>
    RustLib.instance.api.crateFfiDaemonDaemonExtractDaemons();

/// Absolute path to an extracted daemon binary (empty if missing).
String daemonGetDaemonPath({required String daemonName}) => RustLib.instance.api
    .crateFfiDaemonDaemonGetDaemonPath(daemonName: daemonName);

/// Whether all three daemons are extracted.
bool daemonAreDaemonsAvailable() =>
    RustLib.instance.api.crateFfiDaemonDaemonAreDaemonsAvailable();

/// Per-daemon extraction status as JSON: {"i2pd":true,...}.
String daemonGetDaemonStatus() =>
    RustLib.instance.api.crateFfiDaemonDaemonGetDaemonStatus();

/// Extract + launch i2pd (SAM 7656, SOCKS 4447, HTTP 4444), freenet, and
/// rnsd. Each spawn is attempted independently; the result reports per
/// daemon liveness after the spawn attempt.
bool daemonStartDaemons() =>
    RustLib.instance.api.crateFfiDaemonDaemonStartDaemons();

/// Kill any spawned daemons.
bool daemonStopDaemons() =>
    RustLib.instance.api.crateFfiDaemonDaemonStopDaemons();

/// Liveness of the spawned i2pd process.
bool daemonIsI2PdRunning() =>
    RustLib.instance.api.crateFfiDaemonDaemonIsI2PdRunning();

/// Liveness of the spawned rnsd process.
bool daemonIsRnsdRunning() =>
    RustLib.instance.api.crateFfiDaemonDaemonIsRnsdRunning();
