// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `any_daemons_available`, `asset_name`, `bundle_daemons_dir`, `daemons_dir`, `files_dir`, `find_daemon_binary`, `is_daemon_available`, `is_daemon_port_open`, `is_real_binary`, `is_running`, `port_open`, `register_spawner`, `spawn_all`, `spawn`, `watchdog_loop`, `write_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SpawnOutcome`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`

/// Extract the three bundled daemons from assets into files/daemons/.
/// Returns false if extraction is unsupported (no bundled assets).
bool daemonExtractDaemons() =>
    RustLib.instance.api.crateFfiDaemonDaemonExtractDaemons();

/// Absolute path to an extracted daemon binary (empty if missing).
String daemonGetDaemonPath({required String daemonName}) => RustLib.instance.api
    .crateFfiDaemonDaemonGetDaemonPath(daemonName: daemonName);

/// Whether all extracted daemons are present. rnsd on Android ships inside
/// the app (Chaquopy Python, RnsdRunner) — no asset to extract.
bool daemonAreDaemonsAvailable() =>
    RustLib.instance.api.crateFfiDaemonDaemonAreDaemonsAvailable();

/// Per-daemon extraction status as JSON: {"i2pd":true,...}. On Android,
/// `reticulum` reports the in-process Chaquopy daemon's liveness instead of
/// asset presence — the daemon runs inside the app, not as a child process.
String daemonGetDaemonStatus() =>
    RustLib.instance.api.crateFfiDaemonDaemonGetDaemonStatus();

/// Extract + launch i2pd (SAM 7656, SOCKS 4447, HTTP 4444), freenet, and
/// rnsd. Each spawn is attempted independently; the result reports per
/// daemon liveness after the spawn attempt.
bool daemonStartDaemons() =>
    RustLib.instance.api.crateFfiDaemonDaemonStartDaemons();

/// Kill any spawned daemons and stop the foreground service.
bool daemonStopDaemons() =>
    RustLib.instance.api.crateFfiDaemonDaemonStopDaemons();

/// Whether the daemon foreground service is active (Android). Off-Android
/// this reports false and is a no-op.
bool daemonServiceRunning() =>
    RustLib.instance.api.crateFfiDaemonDaemonServiceRunning();

/// Fire the OS "ignore battery optimizations" dialog for this app, so OEM
/// battery managers don't kill the daemon foreground service. Off-Android
/// returns false.
bool daemonRequestBatteryExemption() =>
    RustLib.instance.api.crateFfiDaemonDaemonRequestBatteryExemption();

/// Liveness of the spawned i2pd process or active SAM port.
bool daemonIsI2PdRunning() =>
    RustLib.instance.api.crateFfiDaemonDaemonIsI2PdRunning();

/// Liveness of the spawned rnsd process (Chaquopy thread on Android) or active 4242 port.
bool daemonIsRnsdRunning() =>
    RustLib.instance.api.crateFfiDaemonDaemonIsRnsdRunning();
