// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `card_from_value`, `cards_from_json`, `profile_rows_sql`, `react`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DatingCardInfo`, `ProfileContent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Fetch dating profiles to swipe on: excludes own profile and profiles the
/// user already reacted to (liked/passed).
String datingFetchProfiles({required String userPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiDatingDatingFetchProfiles(
        userPubkey: userPubkey, limit: limit);

/// Fetch a single dating profile by profile event id.
String datingGetProfile({required String profileId}) =>
    RustLib.instance.api.crateFfiDatingDatingGetProfile(profileId: profileId);

/// Create dating profile (kind 30082, `d` = `dating_profile`). Signs with
/// the unlocked signer and returns the signed event JSON for relay publish;
/// also stores the row locally for immediate swipe use.
String datingCreateProfile(
        {required String userPubkey,
        required String name,
        required int age,
        required String location,
        required String bio,
        required String imagesJson,
        required String interestsJson}) =>
    RustLib.instance.api.crateFfiDatingDatingCreateProfile(
        userPubkey: userPubkey,
        name: name,
        age: age,
        location: location,
        bio: bio,
        imagesJson: imagesJson,
        interestsJson: interestsJson);

/// Update dating profile bio/images/interests (a new kind 30082 event;
/// d-tag identity stays, so relays treat it as a replacement).
bool datingUpdateProfile(
        {required String userPubkey,
        required String bio,
        required String imagesJson,
        required String interestsJson}) =>
    RustLib.instance.api.crateFfiDatingDatingUpdateProfile(
        userPubkey: userPubkey,
        bio: bio,
        imagesJson: imagesJson,
        interestsJson: interestsJson);

/// Get the user's own latest profile.
String datingGetOwnProfile({required String userPubkey}) => RustLib.instance.api
    .crateFfiDatingDatingGetOwnProfile(userPubkey: userPubkey);

/// Delete dating profile (soft delete of local row; kind 5 tombstone is the
/// relay-side counterpart).
bool datingDeleteProfile({required String userPubkey}) => RustLib.instance.api
    .crateFfiDatingDatingDeleteProfile(userPubkey: userPubkey);

/// Like a profile (kind 7 reaction with `+`), stored locally + signed for
/// publish. Mutual likes form a match (checked in `dating_fetch_matches`).
bool datingLike({required String userPubkey, required String profileId}) =>
    RustLib.instance.api
        .crateFfiDatingDatingLike(userPubkey: userPubkey, profileId: profileId);

/// Unlike a profile (kind 7 reaction with `-`).
bool datingUnlike({required String userPubkey, required String profileId}) =>
    RustLib.instance.api.crateFfiDatingDatingUnlike(
        userPubkey: userPubkey, profileId: profileId);

/// Superlike (kind 7 reaction with `super`).
bool datingSuperlike({required String userPubkey, required String profileId}) =>
    RustLib.instance.api.crateFfiDatingDatingSuperlike(
        userPubkey: userPubkey, profileId: profileId);

/// Pass/skip a profile: local reaction record with `pass` content; never
/// published to relays.
bool datingPass({required String userPubkey, required String profileId}) =>
    RustLib.instance.api
        .crateFfiDatingDatingPass(userPubkey: userPubkey, profileId: profileId);

/// Fetch profiles that liked the user (`+` reactions on the user's profile
/// events).
String datingFetchLikes({required String userPubkey}) =>
    RustLib.instance.api.crateFfiDatingDatingFetchLikes(userPubkey: userPubkey);

/// Fetch matches: profiles the user liked that also like the user back.
String datingFetchMatches({required String userPubkey}) => RustLib.instance.api
    .crateFfiDatingDatingFetchMatches(userPubkey: userPubkey);

/// Record an unmatch between the user and a dating profile.
bool datingUnmatch({required String userPubkey, required String profileId}) =>
    RustLib.instance.api.crateFfiDatingDatingUnmatch(
        userPubkey: userPubkey, profileId: profileId);

/// Compatibility score via dating-core JSON API (pure policy in Rust).
double datingCalculateScore(
        {required String userPubkey,
        required String targetPubkey,
        required String preferencesJson}) =>
    RustLib.instance.api.crateFfiDatingDatingCalculateScore(
        userPubkey: userPubkey,
        targetPubkey: targetPubkey,
        preferencesJson: preferencesJson);

/// Filter profiles by age/location preferences, delegating the policy to
/// dating-core.
String datingFilterProfiles(
        {required String userPubkey,
        required int minAge,
        required int maxAge,
        required int locationRadiusKm,
        required String interestsJson}) =>
    RustLib.instance.api.crateFfiDatingDatingFilterProfiles(
        userPubkey: userPubkey,
        minAge: minAge,
        maxAge: maxAge,
        locationRadiusKm: locationRadiusKm,
        interestsJson: interestsJson);

/// Dating profile statistics from the local graph.
String datingGetStats({required String userPubkey}) =>
    RustLib.instance.api.crateFfiDatingDatingGetStats(userPubkey: userPubkey);

/// Block a profile: local-only blocklist record (mirrors the desktop
/// `blocks` table).
bool datingBlockProfile(
        {required String userPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiDatingDatingBlockProfile(
        userPubkey: userPubkey, targetPubkey: targetPubkey);

/// Unblock a profile.
bool datingUnblockProfile(
        {required String userPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiDatingDatingUnblockProfile(
        userPubkey: userPubkey, targetPubkey: targetPubkey);

/// Report a profile: stored as a local report row for moderation sync; the
/// report event is emitted by the moderation pipeline.
bool datingReportProfile(
        {required String reporterPubkey,
        required String targetPubkey,
        required String reason}) =>
    RustLib.instance.api.crateFfiDatingDatingReportProfile(
        reporterPubkey: reporterPubkey,
        targetPubkey: targetPubkey,
        reason: reason);
