// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_pubkey`, `chmod_0600`, `db_query_json`, `raw_sql_allowed`, `rows_json`, `rows_to_json_string`, `same_parent_dir`, `upsert_post_row`, `verify_restored_schema`, `with_db_result`, `with_db_string`, `with_db`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TempCleanup`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Initialize (or re-initialize) the database at `db_path`, applying all
/// schema migrations. Safe to call once per app start.
String dbInit({required String dbPath}) =>
    RustLib.instance.api.crateFfiDbDbInit(dbPath: dbPath);

/// Get the current database path, or an error if not initialized.
String dbPath() => RustLib.instance.api.crateFfiDbDbPath();

/// Close the active database connection and clear the DB path.
bool dbClose() => RustLib.instance.api.crateFfiDbDbClose();

/// Get the current schema version from the _migrations table.
PlatformInt64 dbSchemaVersion() =>
    RustLib.instance.api.crateFfiDbDbSchemaVersion();

/// The schema version this build's migration runner produces
/// (db-core `SCHEMA_VERSION`). Clients use it to detect stale binaries
/// without hardcoding a copy.
PlatformInt64 dbExpectedSchemaVersion() =>
    RustLib.instance.api.crateFfiDbDbExpectedSchemaVersion();

/// Repair a stale/out-of-date schema: wipe all tables and re-run migrations
/// from scratch.  Refuses to operate when the DB is already at or ahead of the
/// current `SCHEMA_VERSION` — fresh or current DBs must not be touched.
String dbForceMigrate() => RustLib.instance.api.crateFfiDbDbForceMigrate();

/// Execute a raw SELECT query; rows are returned as a JSON array of objects
/// (column names as keys). Parameter binding is supported with `?1..?N`.
/// The `settings` table is off-limits: pin flags must only change through
/// the pin module (db_set_setting enforces the same deny-list).
String dbQueryRaw({required String sql}) =>
    RustLib.instance.api.crateFfiDbDbQueryRaw(sql: sql);

/// Internal helper: raw SELECT with bound ?N parameters (`Vec<String>`),
/// rows as a JSON array of objects. Not an FFI surface.
Future<String> dbQueryParams(
        {required String sql, required List<String> params}) =>
    RustLib.instance.api.crateFfiDbDbQueryParams(sql: sql, params: params);

/// Execute a raw INSERT/UPDATE/DELETE (no parameters); returns rows affected.
/// The `settings` table is off-limits (see `raw_sql_allowed`).
///
/// ⚠ Security: This function is intentionally disabled — unparameterized SQL
/// writes from Dart are architecturally unsound (text-based guard is fragile).
/// All callers should use parameterized repo functions instead.
/// The generated FFI stub still wires this name; it always returns an error so
/// the Dart side receives a clear failure rather than executing raw SQL.
Future<BigInt> dbExecuteRaw({required String sql}) =>
    RustLib.instance.api.crateFfiDbDbExecuteRaw(sql: sql);

/// Internal helper: raw INSERT/UPDATE/DELETE with bound ?N parameters
/// (`Vec<String>`); returns rows affected. Not an FFI surface.
Future<BigInt> dbExecuteParams(
        {required String sql, required List<String> params}) =>
    RustLib.instance.api.crateFfiDbDbExecuteParams(sql: sql, params: params);

/// Get the row count of a table.
PlatformInt64 dbCount({required String table}) =>
    RustLib.instance.api.crateFfiDbDbCount(table: table);

/// Set a key/value setting (sidebar order, theme, stealth whitelist, PIN
/// flags). Upserts into the `settings` table. PIN-related keys are denied
/// here — only the pin module may write them.
bool dbSetSetting({required String key, required String value}) =>
    RustLib.instance.api.crateFfiDbDbSetSetting(key: key, value: value);

/// Get a setting value by key. PIN-related keys are denied: their values
/// (salt+hash, lockout state) must never leave Rust.
String? dbGetSetting({required String key}) =>
    RustLib.instance.api.crateFfiDbDbGetSetting(key: key);

/// Delete a setting key. PIN-related keys are denied: deleting them would
/// bypass the PIN lockout state machine.
bool dbDeleteSetting({required String key}) =>
    RustLib.instance.api.crateFfiDbDbDeleteSetting(key: key);

/// Storage usage snapshot: db file size + row counts for the main tables
/// (mirrors the legacy `db_get_storage_stats` command).
String dbStorageStats() => RustLib.instance.api.crateFfiDbDbStorageStats();

/// Checkpoint the WAL and copy the database file to `backup_path` (a full
/// file snapshot — the only state SQLite needs for a consistent restore).
///
/// `backup_path` must resolve to the same directory as the current database
/// file; paths outside that directory are rejected to prevent path traversal.
String dbBackup({required String backupPath}) =>
    RustLib.instance.api.crateFfiDbDbBackup(backupPath: backupPath);

/// Restore: close the current handle, replace the file, and reopen with
/// migrations. Any in-flight connection is dropped.
///
/// `backup_path` must resolve to the same directory as the current database
/// file; paths outside that directory are rejected to prevent path traversal
/// and malicious DB injection.
String dbRestore({required String backupPath}) =>
    RustLib.instance.api.crateFfiDbDbRestore(backupPath: backupPath);

/// Get custom profile nodes for a user from the database.
String dbGetCustomProfileNodes({required String pubkey}) =>
    RustLib.instance.api.crateFfiDbDbGetCustomProfileNodes(pubkey: pubkey);

/// Save custom profile for a user to the database.
bool dbSaveCustomProfile(
        {required String pubkey, required String profileJson}) =>
    RustLib.instance.api.crateFfiDbDbSaveCustomProfile(
        pubkey: pubkey, profileJson: profileJson);

/// Delete posts older than `cutoff_secs` (relative to now); returns rows removed.
BigInt dbDeleteOlderThan({required PlatformInt64 cutoffSecs}) =>
    RustLib.instance.api.crateFfiDbDbDeleteOlderThan(cutoffSecs: cutoffSecs);

/// Delete every stored post; returns rows removed.
BigInt dbDeleteAllPosts() => RustLib.instance.api.crateFfiDbDbDeleteAllPosts();

/// Trending hashtags by usage count (JSON rows: tag/pubkey/last_used_at/count).
String dbGetTrendingHashtags({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateFfiDbDbGetTrendingHashtags(limit: limit);

/// Escrow rows where `pubkey` participates as buyer or seller (JSON).
String dbGetEscrowsByParticipant({required String pubkey}) =>
    RustLib.instance.api.crateFfiDbDbGetEscrowsByParticipant(pubkey: pubkey);

/// Purge geohash peer rows not seen within `cutoff_secs_ago`; returns rows removed.
BigInt dbPurgeStaleGeohashPeers({required PlatformInt64 cutoffSecsAgo}) =>
    RustLib.instance.api
        .crateFfiDbDbPurgeStaleGeohashPeers(cutoffSecsAgo: cutoffSecsAgo);
