// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Block a peer IP address in the eBPF kernel / socket filter
bool ebpfBlockIp({required String ip}) =>
    RustLib.instance.api.crateFfiEbpfEbpfBlockIp(ip: ip);

/// Unblock a peer IP address in the eBPF kernel / socket filter
bool ebpfUnblockIp({required String ip}) =>
    RustLib.instance.api.crateFfiEbpfEbpfUnblockIp(ip: ip);

/// Fetch eBPF traffic shaping metrics (dropped packets, nanoseconds saved, active mode)
String ebpfGetStats() => RustLib.instance.api.crateFfiEbpfEbpfGetStats();
