// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `row_json`, `uuid_like`

/// Save an ephemeral media row. `expires_at` is a unix timestamp or 0.
String ephemeralSave(
        {required String messageId,
        required String conversationId,
        required String conversationType,
        required String mediaUrl,
        required String mediaType,
        required String senderPubkey,
        required String recipientPubkey,
        required PlatformInt64 maxViews,
        required PlatformInt64 expiresAt}) =>
    RustLib.instance.api.crateFfiEphemeralEphemeralSave(
        messageId: messageId,
        conversationId: conversationId,
        conversationType: conversationType,
        mediaUrl: mediaUrl,
        mediaType: mediaType,
        senderPubkey: senderPubkey,
        recipientPubkey: recipientPubkey,
        maxViews: maxViews,
        expiresAt: expiresAt);

/// Get one row by id.
String ephemeralGet({required String id}) =>
    RustLib.instance.api.crateFfiEphemeralEphemeralGet(id: id);

/// All pending media addressed to `pubkey`, newest first, as a JSON array.
String ephemeralListPending({required String pubkey}) =>
    RustLib.instance.api.crateFfiEphemeralEphemeralListPending(pubkey: pubkey);

/// View media: increments the counter (expiring at max_views) and returns
/// the fresh row. Errors once the media is expired.
String ephemeralView({required String id}) =>
    RustLib.instance.api.crateFfiEphemeralEphemeralView(id: id);

/// Delete a row.
bool ephemeralDelete({required String id}) =>
    RustLib.instance.api.crateFfiEphemeralEphemeralDelete(id: id);

/// Purge rows whose expiry is in the past; returns removed ids.
List<String> ephemeralCleanExpired() =>
    RustLib.instance.api.crateFfiEphemeralEphemeralCleanExpired();
