// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attendees_count`, `centroid_of`, `d_tag_of`, `event_from_value`, `event_rows_sql`, `events_from_json`, `haversine`, `rsvp_for_user`, `valid_rsvp`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EventContent`, `EventInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Fetch nearby events (distance filter computed client-side over the
/// locally stored event rows; exact haversine, not a coarse box).
String eventsFetchNearby(
        {required double latitude,
        required double longitude,
        required double radiusKm,
        required int limit}) =>
    RustLib.instance.api.crateFfiEventsEventsFetchNearby(
        latitude: latitude,
        longitude: longitude,
        radiusKm: radiusKm,
        limit: limit);

/// Fetch events the user is involved in (created, RSVPed, or attended).
String eventsFetchUserEvents(
        {required String userPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiEventsEventsFetchUserEvents(
        userPubkey: userPubkey, limit: limit);

/// Create an event (kind 31923 calendar event; content per the calendar
/// sync format). Signs with the unlocked signer and stores the row locally.
String eventsCreate(
        {required String creatorPubkey,
        required String title,
        required String description,
        required String location,
        required double latitude,
        required double longitude,
        required BigInt startTime,
        required BigInt endTime,
        required String imageUrl}) =>
    RustLib.instance.api.crateFfiEventsEventsCreate(
        creatorPubkey: creatorPubkey,
        title: title,
        description: description,
        location: location,
        latitude: latitude,
        longitude: longitude,
        startTime: startTime,
        endTime: endTime,
        imageUrl: imageUrl);

/// RSVP to an event (kind 31924, content accepted/declined/pending).
bool eventsRsvp(
        {required String eventId,
        required String userPubkey,
        required String rsvpStatus}) =>
    RustLib.instance.api.crateFfiEventsEventsRsvp(
        eventId: eventId, userPubkey: userPubkey, rsvpStatus: rsvpStatus);

/// Check in to an event. Enforced via events-core `can_checkin`: only
/// within the event window (+ buffer) is the attendance badge signed.
bool eventsCheckIn(
        {required String eventId,
        required String userPubkey,
        required double latitude,
        required double longitude}) =>
    RustLib.instance.api.crateFfiEventsEventsCheckIn(
        eventId: eventId,
        userPubkey: userPubkey,
        latitude: latitude,
        longitude: longitude);

/// Event details: includes local RSVP + attendee counts.
String eventsGetEvent({required String eventId}) =>
    RustLib.instance.api.crateFfiEventsEventsGetEvent(eventId: eventId);

/// Attendees = distinct pubkeys with an `accepted` RSVP (kind 31924).
List<String> eventsGetAttendees({required String eventId}) =>
    RustLib.instance.api.crateFfiEventsEventsGetAttendees(eventId: eventId);

/// All reminder rows, soonest first, as JSON array.
String eventsRemindersList() =>
    RustLib.instance.api.crateFfiEventsEventsRemindersList();

/// Create/update a reminder. Returns the reminder id.
String eventsReminderUpsert(
        {required String reminderId,
        required String eventId,
        required String title,
        required PlatformInt64 startTime,
        required PlatformInt64 minutesBefore}) =>
    RustLib.instance.api.crateFfiEventsEventsReminderUpsert(
        reminderId: reminderId,
        eventId: eventId,
        title: title,
        startTime: startTime,
        minutesBefore: minutesBefore);

/// Delete a reminder.
bool eventsReminderDelete({required String reminderId}) => RustLib.instance.api
    .crateFfiEventsEventsReminderDelete(reminderId: reminderId);
