// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FeedOptions`, `FeedPost`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

/// Aggregate chat reactions from JSON input (delegates to feed-core).
String feedAggregateChatReactions({required String input}) =>
    RustLib.instance.api.crateFfiFeedFeedAggregateChatReactions(input: input);

/// Rank posts for feed display (delegates to feed-core ranking).
/// `events_json`: array of `{stats: {...}, hashtags: []}`; returns ranked
/// indices into the original array.
Future<String> feedRankPosts({required String eventsJson}) =>
    RustLib.instance.api.crateFfiFeedFeedRankPosts(eventsJson: eventsJson);

/// Validate note content (length cap, emptiness) before publishing.
bool feedValidateNote({required String content}) =>
    RustLib.instance.api.crateFfiFeedFeedValidateNote(content: content);

/// Publish a text note (kind 1). Signs with the unlocked signer, sends to
/// relays, or queues in the persistent outbox when offline. Returns the
/// signed event JSON.
Future<String> feedPublishTextNote(
        {required String content, required String tagsJson}) =>
    RustLib.instance.api
        .crateFfiFeedFeedPublishTextNote(content: content, tagsJson: tagsJson);

/// Publish a reply (kind 1 with `e`/`p` tags referencing root/reply ids).
Future<String> feedPublishReply(
        {required String content,
        required String rootEventId,
        required String replyToEventId}) =>
    RustLib.instance.api.crateFfiFeedFeedPublishReply(
        content: content,
        rootEventId: rootEventId,
        replyToEventId: replyToEventId);

/// Create a reaction (kind 7) to an event. Publishes or queues offline.
Future<String> feedCreateReaction(
        {required String eventId, required String reactionType}) =>
    RustLib.instance.api.crateFfiFeedFeedCreateReaction(
        eventId: eventId, reactionType: reactionType);

/// Delete a post (kind 5 deletion request). Publishes or queues offline.
Future<String> feedDeletePost({required String eventId}) =>
    RustLib.instance.api.crateFfiFeedFeedDeletePost(eventId: eventId);

/// Compress event JSON for storage (zstd via content-core). Runs on the
/// Rust async runtime so the UI thread never blocks.
Future<Uint8List> feedCompressEvent({required String eventJson}) =>
    RustLib.instance.api.crateFfiFeedFeedCompressEvent(eventJson: eventJson);

/// Decompress an event stored with `feed_compress_event`.
Future<String> feedDecompressEvent({required List<int> compressed}) =>
    RustLib.instance.api
        .crateFfiFeedFeedDecompressEvent(compressed: compressed);

/// Fetch recent feed posts from the local DB (kind 1, newest first),
/// optionally filtered to posts by the given author.
String feedFetchEvents({required String optionsJson}) =>
    RustLib.instance.api.crateFfiFeedFeedFetchEvents(optionsJson: optionsJson);

/// Fetch a windowed slice of feed posts from DB.
String feedFetchWindow({required int startIndex, required int limit}) =>
    RustLib.instance.api
        .crateFfiFeedFeedFetchWindow(startIndex: startIndex, limit: limit);

/// Fetch a thread (root post + direct replies) from the local DB.
String feedFetchThread({required String eventId}) =>
    RustLib.instance.api.crateFfiFeedFeedFetchThread(eventId: eventId);

/// Pre-calculated layout extents for one feed card. Request:
/// {"id","text":{"content","font_size_px","line_height_factor",
/// "max_width_px","bold","max_lines"},"media":[{"w","h"}],"chrome":{...}}
/// Returns {"id","height_px","text":{"lines","height_px","last_line_width_px",
/// "elided","max_width_px"},"media":[{"height_px","width_px"}],
/// "media_height_px"}.
String feedComputeCardLayout({required String requestJson}) =>
    RustLib.instance.api
        .crateFfiFeedFeedComputeCardLayout(requestJson: requestJson);

/// Batch variant: requests_json = array of card requests; result = array of
/// layout results, in the same order (stable for ListView.builder maps).
String feedComputeCardLayouts({required String requestsJson}) =>
    RustLib.instance.api
        .crateFfiFeedFeedComputeCardLayouts(requestsJson: requestsJson);

/// Build freenet ephemeral tags for a post (JSON out).
String feedFreenetEphemeralTags({required String freenetKey}) =>
    RustLib.instance.api
        .crateFfiFeedFeedFreenetEphemeralTags(freenetKey: freenetKey);

/// Extract profile entry (pubkey/content/created_at) from a nostr event JSON.
String feedProfileEntryFromEvent({required String eventJson}) =>
    RustLib.instance.api
        .crateFfiFeedFeedProfileEntryFromEvent(eventJson: eventJson);
