// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `classify_contents`, `feed_engagement_counters`, `get_custom_word_filters`, `is_content_clean`, `moderation_cache`, `parse_media_dto`, `query_feed_posts_internal`, `query_feed_posts_typed_internal`, `query_thread_posts_internal`, `sync_moderation_filters`, `take_clean_rows`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngagementCounters`, `FeedOptions`, `FeedPost`, `FeedRankItem`, `PostStatsInput`, `SearchIndexRow`, `SignedEventHeader`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Aggregate chat reactions from JSON input (delegates to feed-core).
String feedAggregateChatReactions({required String input}) =>
    RustLib.instance.api.crateFfiFeedFeedAggregateChatReactions(input: input);

/// Rank posts for feed display (delegates to feed-core ranking).
/// `events_json`: array of `{stats: {...}, hashtags: []}`; returns ranked
/// indices into the original array.
Future<String> feedRankPosts({required String eventsJson}) =>
    RustLib.instance.api.crateFfiFeedFeedRankPosts(eventsJson: eventsJson);

/// Validate note content (length cap, emptiness, and AI moderation policy) before publishing.
bool feedValidateNote({required String content}) =>
    RustLib.instance.api.crateFfiFeedFeedValidateNote(content: content);

/// Validate and publish a text note (kind 1): content validation, custom
/// word-filter verdict, and the hashtag/mention/media pipeline through the
/// FTS index. Returns the signed event JSON.
Future<String> feedPublishTextNote(
        {required String content, required String tagsJson}) =>
    RustLib.instance.api
        .crateFfiFeedFeedPublishTextNote(content: content, tagsJson: tagsJson);

/// Publish a reply (kind 1 with `e`/`p` tags referencing root/reply ids).
/// Checks content with on-device AI moderation before publishing.
Future<String> feedPublishReply(
        {required String content,
        required String rootEventId,
        required String replyToEventId}) =>
    RustLib.instance.api.crateFfiFeedFeedPublishReply(
        content: content,
        rootEventId: rootEventId,
        replyToEventId: replyToEventId);

/// Create a reaction (kind 7) to an event. Publishes or queues offline.
Future<String> feedCreateReaction(
        {required String eventId, required String reactionType}) =>
    RustLib.instance.api.crateFfiFeedFeedCreateReaction(
        eventId: eventId, reactionType: reactionType);

/// Delete a post (kind 5 deletion request). Publishes or queues offline.
Future<String> feedDeletePost({required String eventId}) =>
    RustLib.instance.api.crateFfiFeedFeedDeletePost(eventId: eventId);

/// Fetch recent feed posts directly as strongly typed DTOs (zero JSON string parsing).
Future<List<FeedPostDto>> feedFetchEventsTyped(
        {required FeedQueryOptions options}) =>
    RustLib.instance.api.crateFfiFeedFeedFetchEventsTyped(options: options);

/// Observe live feed posts directly as strongly typed DTO streams via FRB SSE binary framing.
Stream<List<FeedPostDto>> feedWatchEventsTyped(
        {required FeedQueryOptions options}) =>
    RustLib.instance.api.crateFfiFeedFeedWatchEventsTyped(options: options);

/// Fetch recent feed posts from the local DB (kind 1, newest first),
/// filtering out posts that trip on-device AI moderation or word filters.
Future<String> feedFetchEvents({required String optionsJson}) =>
    RustLib.instance.api.crateFfiFeedFeedFetchEvents(optionsJson: optionsJson);

/// Observe live feed posts from the local DB. Streams the updated feed posts (JSON)
/// whenever `posts` or `reactions` tables undergo mutation, with automatic debouncing.
Stream<String> feedWatchEvents({required String optionsJson}) =>
    RustLib.instance.api.crateFfiFeedFeedWatchEvents(optionsJson: optionsJson);

/// Fetch a windowed slice of feed posts from DB, filtering moderated items.
Future<String> feedFetchWindow(
        {required int startIndex,
        required int limit,
        required String audience}) =>
    RustLib.instance.api.crateFfiFeedFeedFetchWindow(
        startIndex: startIndex, limit: limit, audience: audience);

/// Fetch a thread (root post + direct replies) from the local DB, filtering moderated replies.
Future<String> feedFetchThread({required String eventId}) =>
    RustLib.instance.api.crateFfiFeedFeedFetchThread(eventId: eventId);

/// Observe live replies and updates for a thread root. Streams updated replies (JSON)
/// whenever `posts` or `reactions` tables undergo mutation, with automatic debouncing.
Stream<String> feedWatchThread({required String eventId}) =>
    RustLib.instance.api.crateFfiFeedFeedWatchThread(eventId: eventId);

/// Pre-calculated layout extents for one feed card. Request:
/// {"id","text":{"content","font_size_px","line_height_factor",
/// "max_width_px","bold","max_lines"},"media":[{"w","h"}],"chrome":{...}}
/// Returns {"id","height_px","text":{"lines","height_px","last_line_width_px",
/// "elided","max_width_px"},"media":[{"height_px","width_px"}],
/// "media_height_px"}.
String feedComputeCardLayout({required String requestJson}) =>
    RustLib.instance.api
        .crateFfiFeedFeedComputeCardLayout(requestJson: requestJson);

/// Batch variant: requests_json = array of card requests; result = array of
/// layout results, in the same order (stable for ListView.builder maps).
String feedComputeCardLayouts({required String requestsJson}) =>
    RustLib.instance.api
        .crateFfiFeedFeedComputeCardLayouts(requestsJson: requestsJson);

/// Strongly typed feed post result (emitted directly across FFI via SSE).
class FeedPostDto {
  final String eventId;
  final String pubkey;
  final String content;
  final BigInt createdAt;
  final int reactions;
  final int replies;
  final int reposts;
  final bool liked;
  final String? profileName;
  final String? profilePicture;
  final PostMediaDto? media;

  const FeedPostDto({
    required this.eventId,
    required this.pubkey,
    required this.content,
    required this.createdAt,
    required this.reactions,
    required this.replies,
    required this.reposts,
    required this.liked,
    this.profileName,
    this.profilePicture,
    this.media,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      pubkey.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      reactions.hashCode ^
      replies.hashCode ^
      reposts.hashCode ^
      liked.hashCode ^
      profileName.hashCode ^
      profilePicture.hashCode ^
      media.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedPostDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          pubkey == other.pubkey &&
          content == other.content &&
          createdAt == other.createdAt &&
          reactions == other.reactions &&
          replies == other.replies &&
          reposts == other.reposts &&
          liked == other.liked &&
          profileName == other.profileName &&
          profilePicture == other.profilePicture &&
          media == other.media;
}

/// Strongly typed feed query options.
class FeedQueryOptions {
  final int limit;
  final int offset;
  final String filterType;
  final PlatformInt64? cursorCreatedAt;
  final String? cursorId;
  final String audience;

  const FeedQueryOptions({
    required this.limit,
    required this.offset,
    required this.filterType,
    this.cursorCreatedAt,
    this.cursorId,
    required this.audience,
  });

  @override
  int get hashCode =>
      limit.hashCode ^
      offset.hashCode ^
      filterType.hashCode ^
      cursorCreatedAt.hashCode ^
      cursorId.hashCode ^
      audience.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedQueryOptions &&
          runtimeType == other.runtimeType &&
          limit == other.limit &&
          offset == other.offset &&
          filterType == other.filterType &&
          cursorCreatedAt == other.cursorCreatedAt &&
          cursorId == other.cursorId &&
          audience == other.audience;
}

/// Strongly typed media attachment for a feed post.
class PostMediaDto {
  final String url;
  final String mediaType;
  final String blobHash;
  final PlatformInt64 size;

  const PostMediaDto({
    required this.url,
    required this.mediaType,
    required this.blobHash,
    required this.size,
  });

  @override
  int get hashCode =>
      url.hashCode ^ mediaType.hashCode ^ blobHash.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PostMediaDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          mediaType == other.mediaType &&
          blobHash == other.blobHash &&
          size == other.size;
}
