// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `member_count`, `row_to_group`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GroupInfo`, `GroupMessageRow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Fetch all groups the user belongs to (DB-backed).
String groupsFetchGroups({required String userPubkey}) => RustLib.instance.api
    .crateFfiGroupsGroupsFetchGroups(userPubkey: userPubkey);

/// Get detailed group info by id.
String groupsGetGroupInfo({required String groupId}) =>
    RustLib.instance.api.crateFfiGroupsGroupsGetGroupInfo(groupId: groupId);

/// Get group members (pubkeys + roles from the membership table).
List<String> groupsGetMembers({required String groupId}) =>
    RustLib.instance.api.crateFfiGroupsGroupsGetMembers(groupId: groupId);

/// Join a group: insert the local membership row (admin approval flows stay
/// relay-side; the local row records intent).
bool groupsJoin({required String groupId, required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiGroupsGroupsJoin(groupId: groupId, userPubkey: userPubkey);

/// Leave a group: remove the local membership row.
bool groupsLeave({required String groupId, required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiGroupsGroupsLeave(groupId: groupId, userPubkey: userPubkey);

/// Sign a kind-1059 group message envelope and persist it to the local
/// `group_messages` table so offline fetches work. Returns the signed event
/// JSON (for relay publish in a later pipeline).
String groupsPostMessage({required String groupId, required String content}) =>
    RustLib.instance.api
        .crateFfiGroupsGroupsPostMessage(groupId: groupId, content: content);

/// Fetch group chat messages from DB with pagination.
String groupsFetchMessages(
        {required String groupId, required int limit, required int offset}) =>
    RustLib.instance.api.crateFfiGroupsGroupsFetchMessages(
        groupId: groupId, limit: limit, offset: offset);

/// Change member role (admin only).
bool groupsSetMemberRole(
        {required String groupId,
        required String memberPubkey,
        required String role,
        required String adminPubkey}) =>
    RustLib.instance.api.crateFfiGroupsGroupsSetMemberRole(
        groupId: groupId,
        memberPubkey: memberPubkey,
        role: role,
        adminPubkey: adminPubkey);

/// Remove member (admin only).
bool groupsRemoveMember(
        {required String groupId,
        required String memberPubkey,
        required String adminPubkey}) =>
    RustLib.instance.api.crateFfiGroupsGroupsRemoveMember(
        groupId: groupId, memberPubkey: memberPubkey, adminPubkey: adminPubkey);

/// List custom roles for a group, ordered by position.
String groupsRolesList({required String groupId}) =>
    RustLib.instance.api.crateFfiGroupsGroupsRolesList(groupId: groupId);

/// Create or update a custom role.
bool groupsRoleUpsert(
        {required String roleId,
        required String groupId,
        required String name,
        required String color,
        required PlatformInt64 position,
        required String permissions}) =>
    RustLib.instance.api.crateFfiGroupsGroupsRoleUpsert(
        roleId: roleId,
        groupId: groupId,
        name: name,
        color: color,
        position: position,
        permissions: permissions);

/// Delete a custom role.
bool groupsRoleDelete({required String roleId}) =>
    RustLib.instance.api.crateFfiGroupsGroupsRoleDelete(roleId: roleId);

/// Members with their role ids (json array of {pubkey, role}).
String groupsMembersWithRoles({required String groupId}) =>
    RustLib.instance.api.crateFfiGroupsGroupsMembersWithRoles(groupId: groupId);

/// Create a group row locally (NIP-29 event publishing is relay-side).
String groupsCreate(
        {required String groupId,
        required String name,
        required String description,
        required String pictureUrl,
        required String creatorPubkey}) =>
    RustLib.instance.api.crateFfiGroupsGroupsCreate(
        groupId: groupId,
        name: name,
        description: description,
        pictureUrl: pictureUrl,
        creatorPubkey: creatorPubkey);
