// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// True only on Android ≥ 26 with a hardware AVC encoder present.
bool h264IsSupported() => RustLib.instance.api.crateFfiH264H264IsSupported();

/// Configure the hardware AVC encoder (I420 in via BGRA conversion).
bool h264InitEncode(
        {required int width,
        required int height,
        required int bitrate,
        required int fps}) =>
    RustLib.instance.api.crateFfiH264H264InitEncode(
        width: width, height: height, bitrate: bitrate, fps: fps);

/// Feed one BGRA frame; returns drained `[flag, ...Annex-B]` blobs.
List<Uint8List> h264FeedEncode({required List<int> bgra}) =>
    RustLib.instance.api.crateFfiH264H264FeedEncode(bgra: bgra);

/// Configure the software AVC decoder (feed Annex-B directly).
bool h264InitDecode() => RustLib.instance.api.crateFfiH264H264InitDecode();

/// Feed one Annex-B NAL blob; returns JPEG frames drained from the decoder.
List<Uint8List> h264FeedDecode({required List<int> nal}) =>
    RustLib.instance.api.crateFfiH264H264FeedDecode(nal: nal);

/// Start the local DVR (MP4 muxer, Kotlin LiveRecorder). Returns the output
/// path or None on failure.
String? h264InitRecord() => RustLib.instance.api.crateFfiH264H264InitRecord();

/// Stop the DVR and seal the MP4. Returns the recorded file path (or None
/// when nothing was recorded).
String? h264StopRecord() => RustLib.instance.api.crateFfiH264H264StopRecord();

/// Stop + release both encoder and decoder if initialized.
bool h264Release() => RustLib.instance.api.crateFfiH264H264Release();
