// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `all_users`, `empty_profile`, `row_to_profile`, `split_nip05`, `verify_nip05_fut`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProfileInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Get a user profile from the local DB (created empty on first sight).
String identityGetProfile({required String pubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityGetProfile(pubkey: pubkey);

/// Upsert a fetched kind-0 profile row into the DB.
bool identityStoreProfile({required String profile}) =>
    RustLib.instance.api.crateFfiIdentityIdentityStoreProfile(profile: profile);

/// Search users by name/about (FTS-ish prefix match).
String identitySearchUsers({required String query, required int limit}) =>
    RustLib.instance.api
        .crateFfiIdentityIdentitySearchUsers(query: query, limit: limit);

/// Get the active account's own profile (alias of `identity_get_profile`).
String identityGetSelfProfile({required String pubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityGetSelfProfile(pubkey: pubkey);

/// Build and sign a kind-0 profile metadata event for the unlocked account.
/// `pubkey` is validated against the unlocked signer; returns signed JSON
/// (publish via `network_publish_event`).
String identityUpdateProfile(
        {required String pubkey,
        required String name,
        required String displayName,
        required String picture,
        required String banner,
        required String about,
        required String nip05}) =>
    RustLib.instance.api.crateFfiIdentityIdentityUpdateProfile(
        pubkey: pubkey,
        name: name,
        displayName: displayName,
        picture: picture,
        banner: banner,
        about: about,
        nip05: nip05);

/// Verify a NIP-05 identifier against the published `.well-known` document.
bool identityVerifyNip05({required String nip05}) =>
    RustLib.instance.api.crateFfiIdentityIdentityVerifyNip05(nip05: nip05);

/// Compute the WoT trust score (0..1) of `target` from `viewer`'s graph,
/// using all stored users' contact lists.
double identityGetTrustScore(
        {required String sourcePubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityGetTrustScore(
        sourcePubkey: sourcePubkey, targetPubkey: targetPubkey);

/// Classify the target as trusted / warning / unknown relative to the
/// viewer (WoT distance 1 = `trusted`, distance 2 = `warning`).
/// Args: (target_pubkey, viewer_pubkey) for UI parity with the desktop
/// command surface.
String identityGetWotStatus(
        {required String targetPubkey, required String viewerPubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityGetWotStatus(
        targetPubkey: targetPubkey, viewerPubkey: viewerPubkey);

/// Sign a kind-3 contact list (follow) event containing the given pubkey.
/// `user_pubkey` must match the unlocked signer.
String identityFollowUser(
        {required String userPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityFollowUser(
        userPubkey: userPubkey, targetPubkey: targetPubkey);

/// Unfollow: publish a contact-list event without the target (an empty list
/// clears the server-side follow set; a full re-publish of remaining follows
/// is server-side reconciliation).
bool identityUnfollowUser(
        {required String userPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityUnfollowUser(
        userPubkey: userPubkey, targetPubkey: targetPubkey);

/// Block a user locally (stored in the blocks table; also enforced by feed
/// and DM filtering).
bool identityBlockUser(
        {required String blockerPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityBlockUser(
        blockerPubkey: blockerPubkey, targetPubkey: targetPubkey);

/// Unblock a user locally.
bool identityUnblockUser(
        {required String blockerPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityUnblockUser(
        blockerPubkey: blockerPubkey, targetPubkey: targetPubkey);

/// Get the local blocked list for a user.
List<String> identityGetBlockedUsers({required String pubkey}) =>
    RustLib.instance.api
        .crateFfiIdentityIdentityGetBlockedUsers(pubkey: pubkey);

/// Check whether `checker_pubkey` has blocked `target_pubkey`.
bool identityIsBlocked(
        {required String checkerPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiIdentityIdentityIsBlocked(
        checkerPubkey: checkerPubkey, targetPubkey: targetPubkey);
