// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Store a huddle post (expiring ephemeral room message).
bool legacyHuddlePostStore(
        {required String huddleId,
        required String pubkey,
        required String content,
        required PlatformInt64 expiresInSecs}) =>
    RustLib.instance.api.crateFfiLegacyLegacyHuddlePostStore(
        huddleId: huddleId,
        pubkey: pubkey,
        content: content,
        expiresInSecs: expiresInSecs);

/// Fetch huddle posts (json array, oldest first; unexpired only).
String legacyHuddlePosts({required String huddleId, required int limit}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyHuddlePosts(huddleId: huddleId, limit: limit);

/// Delete a huddle post by id.
bool legacyHuddlePostDelete({required String postId}) =>
    RustLib.instance.api.crateFfiLegacyLegacyHuddlePostDelete(postId: postId);

/// Add a guestbook entry on a profile.
bool legacyGuestbookAdd(
        {required String profilePubkey,
        required String senderPubkey,
        String? senderName,
        required String content}) =>
    RustLib.instance.api.crateFfiLegacyLegacyGuestbookAdd(
        profilePubkey: profilePubkey,
        senderPubkey: senderPubkey,
        senderName: senderName,
        content: content);

/// Fetch guestbook entries for a profile (json array, newest first).
String legacyGuestbookEntries(
        {required String profilePubkey,
        required int limit,
        required bool onlyApproved}) =>
    RustLib.instance.api.crateFfiLegacyLegacyGuestbookEntries(
        profilePubkey: profilePubkey, limit: limit, onlyApproved: onlyApproved);

/// Approve or hide a guestbook entry.
bool legacyGuestbookSetApproved(
        {required String entryId, required bool approved}) =>
    RustLib.instance.api.crateFfiLegacyLegacyGuestbookSetApproved(
        entryId: entryId, approved: approved);

/// Delete a guestbook entry.
bool legacyGuestbookDelete({required String entryId}) =>
    RustLib.instance.api.crateFfiLegacyLegacyGuestbookDelete(entryId: entryId);

/// Send a live-stream chat message.
bool legacyStreamChatSend(
        {required String streamId,
        required String pubkey,
        required String text}) =>
    RustLib.instance.api.crateFfiLegacyLegacyStreamChatSend(
        streamId: streamId, pubkey: pubkey, text: text);

/// Fetch live-stream chat messages (json array, oldest first).
String legacyStreamChatMessages(
        {required String streamId, required int limit}) =>
    RustLib.instance.api.crateFfiLegacyLegacyStreamChatMessages(
        streamId: streamId, limit: limit);

/// Clear chat for a stream.
bool legacyStreamChatClear({required String streamId}) => RustLib.instance.api
    .crateFfiLegacyLegacyStreamChatClear(streamId: streamId);

/// Store a link preview cache entry.
bool legacyLinkPreviewStore(
        {required String url,
        required String title,
        required String description}) =>
    RustLib.instance.api.crateFfiLegacyLegacyLinkPreviewStore(
        url: url, title: title, description: description);

/// Fetch a cached link preview (null when absent).
String? legacyLinkPreviewGet({required String url}) =>
    RustLib.instance.api.crateFfiLegacyLegacyLinkPreviewGet(url: url);

/// Store an encrypted friend-list backup.
bool legacyFriendBackupStore(
        {required String userPubkey, required String encryptedData}) =>
    RustLib.instance.api.crateFfiLegacyLegacyFriendBackupStore(
        userPubkey: userPubkey, encryptedData: encryptedData);

/// Fetch a friend backup (null when absent).
String? legacyFriendBackupGet({required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyFriendBackupGet(userPubkey: userPubkey);

/// Delete a friend backup.
bool legacyFriendBackupDelete({required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyFriendBackupDelete(userPubkey: userPubkey);

/// Upsert a geohash peer (spatial peer discovery).
bool legacyGeohashPeerUpsert(
        {required String pubkey,
        required String geohash,
        required String purpose}) =>
    RustLib.instance.api.crateFfiLegacyLegacyGeohashPeerUpsert(
        pubkey: pubkey, geohash: geohash, purpose: purpose);

/// List peers by geohash cell (json array).
String legacyGeohashPeersByCell({required String geohash}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyGeohashPeersByCell(geohash: geohash);

/// Purge stale geohash peers (unseen for `stale_secs`).
BigInt legacyGeohashPeersPurge({required PlatformInt64 staleSecs}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyGeohashPeersPurge(staleSecs: staleSecs);

/// Upsert a custom profile node (layout slot). `layout` = JSON
/// `{"row":0,"col":0,"sort":0}`.
bool legacyProfileNodeUpsert(
        {required String id,
        required String userPubkey,
        required String nodeType,
        required String styles,
        required String properties,
        required String layout}) =>
    RustLib.instance.api.crateFfiLegacyLegacyProfileNodeUpsert(
        id: id,
        userPubkey: userPubkey,
        nodeType: nodeType,
        styles: styles,
        properties: properties,
        layout: layout);

/// Fetch custom profile nodes (json array, sort order asc).
String legacyProfileNodes({required String userPubkey}) => RustLib.instance.api
    .crateFfiLegacyLegacyProfileNodes(userPubkey: userPubkey);

/// Delete a custom profile node (or all for a user when id is empty).
BigInt legacyProfileNodeDelete(
        {required String id, required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyProfileNodeDelete(id: id, userPubkey: userPubkey);

/// Mark an item do-not-refetch (e.g. after repeated fetch failures).
bool legacyRefetchBlock({required String id, required String reason}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyRefetchBlock(id: id, reason: reason);

/// Whether an item is marked do-not-refetch.
bool legacyRefetchBlocked({required String id}) =>
    RustLib.instance.api.crateFfiLegacyLegacyRefetchBlocked(id: id);

/// Unblock an item for refetching.
bool legacyRefetchUnblock({required String id}) =>
    RustLib.instance.api.crateFfiLegacyLegacyRefetchUnblock(id: id);

/// Append a diagnostic log entry (device-side capture).
bool legacyDiagnosticLog(
        {required String level,
        required String service,
        required String method,
        required String message}) =>
    RustLib.instance.api.crateFfiLegacyLegacyDiagnosticLog(
        level: level, service: service, method: method, message: message);

/// Fetch diagnostic logs (json array, newest first; optional level filter).
String legacyDiagnosticLogs({required int limit, String? level}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyDiagnosticLogs(limit: limit, level: level);

/// Purge diagnostic logs older than `older_than_secs`.
BigInt legacyDiagnosticPurge({required PlatformInt64 olderThanSecs}) =>
    RustLib.instance.api
        .crateFfiLegacyLegacyDiagnosticPurge(olderThanSecs: olderThanSecs);
