// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db_listings`, `listing_from_value`, `listings_sql`, `order_from_value`, `parse_listings`, `uuid_like`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ListingContent`, `ListingInfo`, `OrderInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Fetch all active listings (newest first).
String marketplaceFetchListings({required int limit, required int offset}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceFetchListings(
        limit: limit, offset: offset);

/// Full-text search on listing content (title/description).
String marketplaceSearch({required String query, required int limit}) =>
    RustLib.instance.api
        .crateFfiMarketplaceMarketplaceSearch(query: query, limit: limit);

/// Get listing by id.
String marketplaceGetListing({required String listingId}) =>
    RustLib.instance.api
        .crateFfiMarketplaceMarketplaceGetListing(listingId: listingId);

/// Get raw listing content JSON string by listing id.
String marketplaceGetContent({required String listingId}) =>
    RustLib.instance.api
        .crateFfiMarketplaceMarketplaceGetContent(listingId: listingId);

/// Create a listing (kind 30402). Signs with the unlocked signer and
/// returns the signed event JSON; also stores the row locally so offline
/// fetches work. Relay publish happens via `network_publish_event`.
String marketplaceCreateListing(
        {required String sellerPubkey,
        required String title,
        required String description,
        required BigInt price,
        required String currency,
        required String category,
        required String condition,
        required String imagesJson,
        required bool shippingAvailable}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceCreateListing(
        sellerPubkey: sellerPubkey,
        title: title,
        description: description,
        price: price,
        currency: currency,
        category: category,
        condition: condition,
        imagesJson: imagesJson,
        shippingAvailable: shippingAvailable);

/// Update listing title/description/price (keeps d-tag identity). Locally
/// the row is replaced; publishing the new signed event is the caller's job.
bool marketplaceUpdateListing(
        {required String listingId,
        required String sellerPubkey,
        required String title,
        required String description,
        required BigInt price}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceUpdateListing(
        listingId: listingId,
        sellerPubkey: sellerPubkey,
        title: title,
        description: description,
        price: price);

/// Mark a listing deleted (soft delete; kind 5 tombstones stay relay-side).
bool marketplaceDeleteListing(
        {required String listingId, required String sellerPubkey}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceDeleteListing(
        listingId: listingId, sellerPubkey: sellerPubkey);

/// Fetch seller's listings.
String marketplaceFetchSellerListings({required String sellerPubkey}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceFetchSellerListings(
        sellerPubkey: sellerPubkey);

/// Get listings by category (t tag).
String marketplaceGetByCategory(
        {required String category, required int limit}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceGetByCategory(
        category: category, limit: limit);

/// Trending listings: most reposts/reactions in the local DB, newest first
/// as tiebreak.
String marketplaceGetTrending({required int limit}) => RustLib.instance.api
    .crateFfiMarketplaceMarketplaceGetTrending(limit: limit);

/// Create an order for a listing (kind 30403 row + local insert).
String marketplaceCreateOrder(
        {required String listingId,
        required String buyerPubkey,
        required String sellerPubkey}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceCreateOrder(
        listingId: listingId,
        buyerPubkey: buyerPubkey,
        sellerPubkey: sellerPubkey);

/// Get order details.
String marketplaceGetOrder({required String orderId}) => RustLib.instance.api
    .crateFfiMarketplaceMarketplaceGetOrder(orderId: orderId);

/// Fetch buyer's orders (posts where the order row's pubkey is the buyer).
String marketplaceFetchBuyerOrders({required String buyerPubkey}) => RustLib
    .instance.api
    .crateFfiMarketplaceMarketplaceFetchBuyerOrders(buyerPubkey: buyerPubkey);

/// Fetch seller's orders (orders whose listing the seller owns, or whose
/// content `seller` field matches).
String marketplaceFetchSellerOrders({required String sellerPubkey}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceFetchSellerOrders(
        sellerPubkey: sellerPubkey);

/// Create an escrow for an order (dedicated escrows table + lifecycle
/// validation from marketplace-core).
String marketplaceCreateEscrow(
        {required String orderId,
        required String buyerPubkey,
        required String sellerPubkey,
        required BigInt amount}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceCreateEscrow(
        orderId: orderId,
        buyerPubkey: buyerPubkey,
        sellerPubkey: sellerPubkey,
        amount: amount);

/// Release escrow funds. Policy comes from marketplace-core: both parties
/// must confirm unless a dispute is active (then arbitrator approval is
/// required) — single-side release is never allowed. The local row records
/// the buyer-side confirmation; the seller confirm travels via the seller's
/// app (kind 30402 event), so the escrow state machine stays conservative
/// here and always refuses unilateral release.
bool marketplaceReleaseEscrow(
        {required String escrowId, required String sellerPubkey}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceReleaseEscrow(
        escrowId: escrowId, sellerPubkey: sellerPubkey);

/// Mark an escrow disputed.
bool marketplaceDisputeEscrow(
        {required String escrowId,
        required String disputerPubkey,
        required String reason}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceDisputeEscrow(
        escrowId: escrowId, disputerPubkey: disputerPubkey, reason: reason);

/// Resolve a disputed escrow in favor of a party (mediator role is gated
/// by the caller; state transitions enforce parties).
bool marketplaceResolveEscrow(
        {required String escrowId,
        required String mediatorPubkey,
        required String winnerPubkey}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceResolveEscrow(
        escrowId: escrowId,
        mediatorPubkey: mediatorPubkey,
        winnerPubkey: winnerPubkey);

/// Get escrow state by id (raw JSON).
String marketplaceGetEscrow({required String escrowId}) => RustLib.instance.api
    .crateFfiMarketplaceMarketplaceGetEscrow(escrowId: escrowId);

/// Latest escrow for a listing (null JSON if none exists).
String marketplaceGetEscrowByListing({required String listingId}) =>
    RustLib.instance.api
        .crateFfiMarketplaceMarketplaceGetEscrowByListing(listingId: listingId);

/// Store a review for a listing (dedicated marketplace_reviews table).
bool marketplaceReviewListing(
        {required String listingId,
        required String reviewerPubkey,
        required PlatformInt64 rating,
        required String text}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceReviewListing(
        listingId: listingId,
        reviewerPubkey: reviewerPubkey,
        rating: rating,
        text: text);

/// Reviews for a listing (newest first): array of
/// `{"rating": N, "reviewer": <pubkey>, "text": <text>}`.
String marketplaceListingReviews(
        {required String listingId, required PlatformInt64 limit}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplaceListingReviews(
        listingId: listingId, limit: limit);

/// Average rating for a listing (0.0 if none).
double marketplaceListingRating({required String listingId}) =>
    RustLib.instance.api
        .crateFfiMarketplaceMarketplaceListingRating(listingId: listingId);

/// Create a poll; options_json is an array of strings. Returns
/// `{"id": ..., "question": ...}`.
String marketplacePollCreate(
        {required String userPubkey,
        required String question,
        required String optionsJson,
        required PlatformInt64 expiresInHours}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplacePollCreate(
        userPubkey: userPubkey,
        question: question,
        optionsJson: optionsJson,
        expiresInHours: expiresInHours);

/// Cast a vote for a poll option.
bool marketplacePollVote(
        {required String pollId,
        required String voterPubkey,
        required PlatformInt64 optionIndex}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplacePollVote(
        pollId: pollId, voterPubkey: voterPubkey, optionIndex: optionIndex);

/// Close a poll; only the poll owner may close it.
bool marketplacePollClose(
        {required String pollId, required String userPubkey}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplacePollClose(
        pollId: pollId, userPubkey: userPubkey);

/// Poll with vote counts: `{"id": ..., "question": ..., "votes": [...]}`.
String marketplacePollGet({required String pollId}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplacePollGet(pollId: pollId);

/// Whether a voter has voted in a poll.
bool marketplacePollHasVoted(
        {required String pollId, required String voterPubkey}) =>
    RustLib.instance.api.crateFfiMarketplaceMarketplacePollHasVoted(
        pollId: pollId, voterPubkey: voterPubkey);
