// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_cache_filename`, `infer_mime_type`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MEDIA_SERVER`, `MediaResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `fmt`, `fmt`, `initialize`

/// Decode raw image bytes/file path into uncompressed 32-bit RGBA pixels on a background worker thread.
Future<DecodedImageRgbaDto> mediaDecodeImageRgba(
        {required String filePathOrUrl, int? maxWidth, int? maxHeight}) =>
    RustLib.instance.api.crateFfiMediaMediaDecodeImageRgba(
        filePathOrUrl: filePathOrUrl, maxWidth: maxWidth, maxHeight: maxHeight);

/// Upload media to a Blossom server. `source` is a local file path or an
/// `http(s)://` URL (SSRF-guarded fetch).
Future<String> mediaUpload(
        {required String filePath, required String blossomServer}) =>
    RustLib.instance.api.crateFfiMediaMediaUpload(
        filePath: filePath, blossomServer: blossomServer);

/// Fetch media from URL and cache locally, returning the cache path.
Future<String> mediaFetch({required String url, required String cacheDir}) =>
    RustLib.instance.api.crateFfiMediaMediaFetch(url: url, cacheDir: cacheDir);

/// Load media from cache or disk
Future<Uint8List> mediaLoadLocal({required String filePath}) =>
    RustLib.instance.api.crateFfiMediaMediaLoadLocal(filePath: filePath);

/// Get MIME type from file path
Future<String> mediaGetMimeType({required String filePath}) =>
    RustLib.instance.api.crateFfiMediaMediaGetMimeType(filePath: filePath);

/// Clear media cache directory
Future<String> mediaClearCache({required String cacheDir}) =>
    RustLib.instance.api.crateFfiMediaMediaClearCache(cacheDir: cacheDir);

/// Upload media to the local chunk store and return the blob manifest.
/// The blob is chunked, deduplicated, and stored in the local CAS.
String mediaUploadBlob({required List<int> data}) =>
    RustLib.instance.api.crateFfiMediaMediaUploadBlob(data: data);

/// Upload a local media file (or remote URL, SSRF-guarded) directly to the
/// chunk store (zero Dart heap memory overhead for the file path case).
String mediaUploadBlobFile({required String filePath}) =>
    RustLib.instance.api.crateFfiMediaMediaUploadBlobFile(filePath: filePath);

/// Fetch a blob by hash from the chunk store (local or swarm).
/// Returns the manifest JSON with success status.
String mediaFetchBlob({required String blobHash, required String outPath}) =>
    RustLib.instance.api
        .crateFfiMediaMediaFetchBlob(blobHash: blobHash, outPath: outPath);

/// Get the cache path for the chunk store.
String mediaGetCachePath() =>
    RustLib.instance.api.crateFfiMediaMediaGetCachePath();

/// Start a local HTTP range server for media playback (sendfile zero-copy).
/// Binds 127.0.0.1 on an ephemeral port; `/blob/<hash>` serves blob files out
/// of the chunk-store cache directory.
BigInt mediaStartLocalServer() =>
    RustLib.instance.api.crateFfiMediaMediaStartLocalServer();

/// Stop the local HTTP range server.
bool mediaStopLocalServer() =>
    RustLib.instance.api.crateFfiMediaMediaStopLocalServer();

/// Infer an image format (png/jpeg/gif/webp/…) from raw bytes, if recognizable.
String? mediaDetectImageFormat({required List<int> bytes}) =>
    RustLib.instance.api.crateFfiMediaMediaDetectImageFormat(bytes: bytes);

/// Content-aware chunking window for a MIME type (JSON: min/avg/max).
String mediaChunkingForMime({required String mime}) =>
    RustLib.instance.api.crateFfiMediaMediaChunkingForMime(mime: mime);

/// Trim media caches under memory pressure (0 = normal, 1 = moderate, 2 = critical).
bool mediaTrimCaches({required int level}) =>
    RustLib.instance.api.crateFfiMediaMediaTrimCaches(level: level);

/// Whether the global prefetcher would fetch media for a given list index.
bool mediaShouldPrefetch({required int itemIndex}) =>
    RustLib.instance.api.crateFfiMediaMediaShouldPrefetch(itemIndex: itemIndex);

/// Feed scroll telemetry into the global prefetcher (velocity px/s + visible indices).
bool mediaUpdateScrollTelemetry(
        {required double velocity,
        required int topIndex,
        required int bottomIndex}) =>
    RustLib.instance.api.crateFfiMediaMediaUpdateScrollTelemetry(
        velocity: velocity, topIndex: topIndex, bottomIndex: bottomIndex);

/// Encode a thumbhash (hex) from raw image bytes.
String mediaEncodeThumbhash({required List<int> bytes}) =>
    RustLib.instance.api.crateFfiMediaMediaEncodeThumbhash(bytes: bytes);

/// Freenet chunking pass (JSON in, JSON out).
String mediaChunkMediaJson({required String input}) =>
    RustLib.instance.api.crateFfiMediaMediaChunkMediaJson(input: input);

/// Freenet chunk verification pass (JSON in, JSON out).
String mediaVerifyChunkJson({required String input}) =>
    RustLib.instance.api.crateFfiMediaMediaVerifyChunkJson(input: input);

/// Freenet chunk reconstruction pass (JSON in, JSON out).
String mediaReconstructMediaJson({required String input}) =>
    RustLib.instance.api.crateFfiMediaMediaReconstructMediaJson(input: input);

class DecodedImageRgbaDto {
  final int width;
  final int height;
  final Uint8List pixels;

  const DecodedImageRgbaDto({
    required this.width,
    required this.height,
    required this.pixels,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedImageRgbaDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pixels == other.pixels;
}
