// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `conv_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DirectMessage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Send a direct message (NIP-44 v2, kind 4): encrypt with the unlocked
/// signer, build the event, and return signed JSON (publish via
/// `network_publish_event`).
Future<String> messagingSendDm(
        {required String content, required String recipientPubkey}) =>
    RustLib.instance.api.crateFfiMessagingMessagingSendDm(
        content: content, recipientPubkey: recipientPubkey);

/// Decrypt a DM payload from `sender_pubkey` with the unlocked signer key.
String messagingDecryptDm(
        {required String payload, required String senderPubkey}) =>
    RustLib.instance.api.crateFfiMessagingMessagingDecryptDm(
        payload: payload, senderPubkey: senderPubkey);

/// Fetch the most recent DMs with a peer from the local DB (both directions,
/// newest first).
String messagingFetchDms({required String withPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiMessagingMessagingFetchDms(
        withPubkey: withPubkey, limit: limit);

/// Fetch all conversation partner pubkeys for the active account, most
/// recent first.
List<String> messagingFetchConversations({required String pubkey}) =>
    RustLib.instance.api
        .crateFfiMessagingMessagingFetchConversations(pubkey: pubkey);

/// Store a received DM row locally (called by the sync loop after
/// `messaging_decrypt_dm` + verification).
bool messagingStoreDm(
        {required String id,
        required String sender,
        required String recipient,
        required String content,
        required BigInt createdAt,
        required String tagsJson}) =>
    RustLib.instance.api.crateFfiMessagingMessagingStoreDm(
        id: id,
        sender: sender,
        recipient: recipient,
        content: content,
        createdAt: createdAt,
        tagsJson: tagsJson);

/// Encrypt a group DM payload for the legacy kind-1059 path (participants
/// handled server-side); signs and returns event JSON.
String messagingSendGroupDm(
        {required String content,
        required String groupId,
        required String participantPubkeysJson}) =>
    RustLib.instance.api.crateFfiMessagingMessagingSendGroupDm(
        content: content,
        groupId: groupId,
        participantPubkeysJson: participantPubkeysJson);
