// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `conv_id`, `extract_peers_from_cids`, `fetch_conversations_for_account`, `fetch_dms_for_conversation_typed`, `fetch_dms_for_conversation`, `reply_to_from_tags_json`, `seal_dm_content_with_key`, `seal_dm_content`, `unseal_dm_content_with_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DirectMessage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Send a direct message (NIP-44 v2, kind 4): encrypt with the unlocked
/// signer, build the event, and return signed JSON (publish via
/// `network_publish_event`).
///
/// # Security (M4 fix)
/// `content` is wrapped in `Zeroizing<String>` at function entry so that the
/// plaintext heap allocation is zeroed on **every** return path (early-error or
/// normal completion). The clone passed to `messaging_store_dm` is consumed by
/// `seal_dm_content` (AES-256-GCM); the original allocation is zeroed here.
Future<String> messagingSendDm(
        {required String content, required String recipientPubkey}) =>
    RustLib.instance.api.crateFfiMessagingMessagingSendDm(
        content: content, recipientPubkey: recipientPubkey);

/// Fetch the most recent DMs with a peer directly as strongly typed DTOs (zero JSON string parsing).
List<DirectMessageDto> messagingFetchDmsTyped(
        {required String withPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiMessagingMessagingFetchDmsTyped(
        withPubkey: withPubkey, limit: limit);

/// Observe live direct messages with a peer directly as strongly typed DTO streams via FRB SSE binary framing.
Stream<List<DirectMessageDto>> messagingWatchDmsTyped(
        {required String withPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiMessagingMessagingWatchDmsTyped(
        withPubkey: withPubkey, limit: limit);

/// Fetch the most recent DMs with a peer from the local DB (both directions,
/// newest first).
String messagingFetchDms({required String withPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiMessagingMessagingFetchDms(
        withPubkey: withPubkey, limit: limit);

/// Observe live direct messages with a peer. Streams the updated message list (JSON)
/// whenever new messages arrive or are deleted, with automatic debouncing.
Stream<String> messagingWatchDms(
        {required String withPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiMessagingMessagingWatchDms(
        withPubkey: withPubkey, limit: limit);

/// Fetch all conversation partner pubkeys for the active account, most
/// recent first. Reads the maintained `conversations` table (v011) instead
/// of scanning + grouping every message row.
List<String> messagingFetchConversations({required String pubkey}) =>
    RustLib.instance.api
        .crateFfiMessagingMessagingFetchConversations(pubkey: pubkey);

/// Observe live conversation partner pubkeys for the active account.
/// Emits the updated list of peer pubkeys whenever messages change or blocks are updated.
Stream<List<String>> messagingWatchConversations({required String pubkey}) =>
    RustLib.instance.api
        .crateFfiMessagingMessagingWatchConversations(pubkey: pubkey);

/// Store a received DM row locally (called by the sync loop after
/// `messaging_decrypt_dm` + verification).
bool messagingStoreDm(
        {required String id,
        required String sender,
        required String recipient,
        required String content,
        required BigInt createdAt,
        required String tagsJson}) =>
    RustLib.instance.api.crateFfiMessagingMessagingStoreDm(
        id: id,
        sender: sender,
        recipient: recipient,
        content: content,
        createdAt: createdAt,
        tagsJson: tagsJson);

/// Store a batch of received DM rows (live-stream bursts). One FFI crossing
/// + one transaction-ish upsert loop instead of one call per message.
bool messagingStoreDms({required String dmsJson}) =>
    RustLib.instance.api.crateFfiMessagingMessagingStoreDms(dmsJson: dmsJson);

/// Encrypt a group DM payload for the legacy kind-1059 path (participants
/// handled server-side); signs and returns event JSON.
String messagingSendGroupDm(
        {required String content,
        required String groupId,
        required String participantPubkeysJson}) =>
    RustLib.instance.api.crateFfiMessagingMessagingSendGroupDm(
        content: content,
        groupId: groupId,
        participantPubkeysJson: participantPubkeysJson);

/// Strongly typed direct message DTO for reactive FFI streams.
class DirectMessageDto {
  final String id;
  final String sender;
  final String recipient;
  final String content;
  final BigInt createdAt;
  final bool decrypted;
  final bool isOwn;
  final String tags;

  const DirectMessageDto({
    required this.id,
    required this.sender,
    required this.recipient,
    required this.content,
    required this.createdAt,
    required this.decrypted,
    required this.isOwn,
    required this.tags,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      recipient.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      decrypted.hashCode ^
      isOwn.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirectMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          recipient == other.recipient &&
          content == other.content &&
          createdAt == other.createdAt &&
          decrypted == other.decrypted &&
          isOwn == other.isOwn &&
          tags == other.tags;
}
