// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<String> minisFetch() => RustLib.instance.api.crateFfiMinisMinisFetch();

/// Execute a WASI 0.2 Wasm content filter component plugin.
String minisWasmExecuteFilter(
        {required String pluginId,
        required String text,
        required String wasmBytesHex}) =>
    RustLib.instance.api.crateFfiMinisMinisWasmExecuteFilter(
        pluginId: pluginId, text: text, wasmBytesHex: wasmBytesHex);

/// Execute a WASI 0.2 Wasm feed ranker component plugin.
List<String> minisWasmRankFeed(
        {required String pluginId,
        required List<String> postsJson,
        required String wasmBytesHex}) =>
    RustLib.instance.api.crateFfiMinisMinisWasmRankFeed(
        pluginId: pluginId, postsJson: postsJson, wasmBytesHex: wasmBytesHex);
