// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `muted_list_key`, `parse_pubkey_list`, `uuid_like`

/// Mute a user (per-account settings list; never yourself).
bool moderationMuteUser(
        {required String muterPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiModerationModerationMuteUser(
        muterPubkey: muterPubkey, targetPubkey: targetPubkey);

/// Unmute a user.
bool moderationUnmuteUser(
        {required String muterPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiModerationModerationUnmuteUser(
        muterPubkey: muterPubkey, targetPubkey: targetPubkey);

/// Block a user (blocks table; never yourself).
bool moderationBlockUser(
        {required String blockerPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiModerationModerationBlockUser(
        blockerPubkey: blockerPubkey, targetPubkey: targetPubkey);

/// Unblock a user.
bool moderationUnblockUser(
        {required String blockerPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiModerationModerationUnblockUser(
        blockerPubkey: blockerPubkey, targetPubkey: targetPubkey);

/// Get muted users for an account.
List<String> moderationGetMuted({required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiModerationModerationGetMuted(userPubkey: userPubkey);

/// Get blocked users for an account.
List<String> moderationGetBlocked({required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiModerationModerationGetBlocked(userPubkey: userPubkey);

/// Whether the user has blocked or muted `target_pubkey`.
bool moderationIsRestricted(
        {required String actorPubkey, required String targetPubkey}) =>
    RustLib.instance.api.crateFfiModerationModerationIsRestricted(
        actorPubkey: actorPubkey, targetPubkey: targetPubkey);

/// Report content: stored as a local record so the moderation sync loop can
/// emit the report event; returns without relay interaction.
bool moderationReportContent(
        {required String reporterPubkey,
        required String contentType,
        required String contentId,
        required String reason}) =>
    RustLib.instance.api.crateFfiModerationModerationReportContent(
        reporterPubkey: reporterPubkey,
        contentType: contentType,
        contentId: contentId,
        reason: reason);

/// List spam reports for a target pubkey (newest first), as a JSON array
/// with `id`, `pubkey` and `reason` per item.
String moderationListReports(
        {required String targetPubkey, required PlatformInt64 limit}) =>
    RustLib.instance.api.crateFfiModerationModerationListReports(
        targetPubkey: targetPubkey, limit: limit);

/// Delete a spam report by id.
bool moderationDeleteReport({required String reportId}) => RustLib.instance.api
    .crateFfiModerationModerationDeleteReport(reportId: reportId);

/// Check whether a piece of content should be hidden (moderation-core
/// check_text policy + word-list semantics on the Rust side).
bool moderationShouldFilter(
        {required String content, required String userPubkey}) =>
    RustLib.instance.api.crateFfiModerationModerationShouldFilter(
        content: content, userPubkey: userPubkey);

/// Get the active word filter list (device-global moderation settings key).
List<String> moderationGetWordFilters() =>
    RustLib.instance.api.crateFfiModerationModerationGetWordFilters();

/// Update the word filter list.
bool moderationSetWordFilters({required String filtersJson}) =>
    RustLib.instance.api
        .crateFfiModerationModerationSetWordFilters(filtersJson: filtersJson);

/// Create a FROST threshold jury case for community moderation.
String moderationCreateJuryCase(
        {required String caseId,
        required String targetPubkey,
        required String reason,
        required int threshold,
        required int totalJurors,
        required String groupPubkey}) =>
    RustLib.instance.api.crateFfiModerationModerationCreateJuryCase(
        caseId: caseId,
        targetPubkey: targetPubkey,
        reason: reason,
        threshold: threshold,
        totalJurors: totalJurors,
        groupPubkey: groupPubkey);

/// Submit a juror's partial signature vote to a moderation jury case.
String moderationSubmitJuryVote(
        {required String caseJson, required String voteShareJson}) =>
    RustLib.instance.api.crateFfiModerationModerationSubmitJuryVote(
        caseJson: caseJson, voteShareJson: voteShareJson);
