// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_tag`

/// Publish a track (kind 31022). `audio_url` must be a valid https media
/// URL. Returns the event id.
Future<String> musicPublish(
        {required String audioUrl,
        String? title,
        String? thumbnail,
        required List<String> hashtags,
        String? audience}) =>
    RustLib.instance.api.crateFfiMusicMusicPublish(
        audioUrl: audioUrl,
        title: title,
        thumbnail: thumbnail,
        hashtags: hashtags,
        audience: audience);

/// Fetch tracks (kind 31022), optionally by author. Returns JSON array of
/// musicloud entries, newest first.
Future<String> musicFetch({required BigInt limit, String? author}) =>
    RustLib.instance.api.crateFfiMusicMusicFetch(limit: limit, author: author);

/// Share a track as a kind-1 text note with the standard track tags.
Future<String> musicShareToFeed(
        {required String trackId,
        required String trackPubkey,
        required String message,
        required List<String> hashtags}) =>
    RustLib.instance.api.crateFfiMusicMusicShareToFeed(
        trackId: trackId,
        trackPubkey: trackPubkey,
        message: message,
        hashtags: hashtags);

/// Publish a comment on a track (kind 1 with `E`/`a` tags to the track).
Future<String> musicComment(
        {required int trackKind,
        required String trackPubkey,
        required String trackD,
        required String content}) =>
    RustLib.instance.api.crateFfiMusicMusicComment(
        trackKind: trackKind,
        trackPubkey: trackPubkey,
        trackD: trackD,
        content: content);

/// Fetch comments (kind 1 with `E` = track address) for a track.
/// Returns JSON array of mini event outputs.
Future<String> musicComments(
        {required int trackKind,
        required String trackPubkey,
        required String trackD}) =>
    RustLib.instance.api.crateFfiMusicMusicComments(
        trackKind: trackKind, trackPubkey: trackPubkey, trackD: trackD);
