// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client_guard`, `connect_i2p`, `freenet_current`, `freenet_stored`, `get_or_rebuild_http3_client`, `i2p_active`, `i2p_socks_addr`, `managed_sam_endpoint`, `relay_status_snapshot`, `resolved_kind`, `reticulum_started`, `transport_mode`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RelayInfo`, `ReticulumStatusDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Perform a network request via the HTTP/3 & QUIC network stack.
/// Defense-in-depth: the SSRF policy runs here AND inside `Http3Client::request`
/// (private/loopback/link-local/DNS-rebinding hosts rejected), so a hijacked
/// Dart layer can't turn this surface into an internal-network egress.
Future<HttpResponseDto> networkFetchHttp3(
        {required String url,
        required String method,
        required String headersJson,
        Uint8List? body}) =>
    RustLib.instance.api.crateFfiNetworkNetworkFetchHttp3(
        url: url, method: method, headersJson: headersJson, body: body);

/// Initialize the relay client and connect to the given relays.
Future<String> networkInitRelays({required List<String> relayUrls}) =>
    RustLib.instance.api.crateFfiNetworkNetworkInitRelays(relayUrls: relayUrls);

/// Add and connect a single relay.
Future<bool> networkAddRelay({required String url}) =>
    RustLib.instance.api.crateFfiNetworkNetworkAddRelay(url: url);

/// Remove (disconnect) a relay.
Future<bool> networkRemoveRelay({required String url}) =>
    RustLib.instance.api.crateFfiNetworkNetworkRemoveRelay(url: url);

/// Snapshot of relay connection state (url, connected, latency, last event).
Future<String> networkGetRelayStatus() =>
    RustLib.instance.api.crateFfiNetworkNetworkGetRelayStatus();

/// Summary of relay connectivity: `{connected, total}` — drives the app-wide
/// offline banner. One relay connected means we are online.
///
/// Mesh transports (reticulum/freenet/i2p) carry traffic without the wss relay
/// client. The mesh "online" exemption must come from the mesh relay node
/// actually running (`relay::mesh_running`), NOT from the transport probe —
/// a bind probe only proves a daemon socket is open, not that egress works, so
/// a probe-satisfied-but-dead transport would otherwise force the banner
/// green. With the mesh node stopped, zero connected relays means offline,
/// honestly.
Future<String> networkRelayConnectionStatus() =>
    RustLib.instance.api.crateFfiNetworkNetworkRelayConnectionStatus();

/// Subscribe to events matching a NIP-01 filter JSON object. Returns the
/// subscription id; events are polled with `network_take_events`.
/// On a mesh transport the subscription is a no-op success: flood gossip
/// ingest already delivers everything to the local DB/stream continuously.
Future<String> networkSubscribe({required String filterJson}) =>
    RustLib.instance.api
        .crateFfiNetworkNetworkSubscribe(filterJson: filterJson);

/// Unsubscribe a subscription id. No-op success on a mesh transport.
Future<bool> networkUnsubscribe({required String subscriptionId}) =>
    RustLib.instance.api
        .crateFfiNetworkNetworkUnsubscribe(subscriptionId: subscriptionId);

/// Publish an already-signed event (JSON) to all connected relays.
/// Returns the number of relays that accepted it; Err when no relay
/// accepted (event never reached the network — callers must surface or
/// retry, never claim success).
/// Mesh transports publish via the mesh relay node (flood) first.
Future<int> networkPublishEvent({required String eventJson}) =>
    RustLib.instance.api
        .crateFfiNetworkNetworkPublishEvent(eventJson: eventJson);

/// Query events matching a filter against relays and the local cache.
/// Returns an array of event JSON objects.
/// On a mesh transport, queries the flood-gossip recent window (verified +
/// filter-matched) instead of the wss relay client.
Future<String> networkQueryEvents({required String filterJson}) =>
    RustLib.instance.api
        .crateFfiNetworkNetworkQueryEvents(filterJson: filterJson);

/// Raw TCP probe: is the local i2pd SOCKS proxy (port 7656, `.i2p` reach)
/// listening? Exposed so the Flutter UI can show tunnel status.
Future<bool> networkI2PStatus() =>
    RustLib.instance.api.crateFfiNetworkNetworkI2PStatus();

/// Raw TCP probe: is a local Freenet gateway (default WS-API port 7509)
/// listening?
Future<bool> networkFreenetStatus() =>
    RustLib.instance.api.crateFfiNetworkNetworkFreenetStatus();

/// Current transport mode: `"default"`, `"reticulum"`, `"freenet"`,
/// `"i2p"`, or `"nostr"` (legacy `"clearnet"`/`"auto"` accepted on set).
String networkGetTransportMode() =>
    RustLib.instance.api.crateFfiNetworkNetworkGetTransportMode();

/// Resolved transport status: JSON `{mode, resolved, satisfied}`. `resolved`
/// is the concrete transport in use after probing (Default chain + "only"
/// fallbacks); `satisfied` is false when a preferred transport is down.
String networkGetResolvedTransport() =>
    RustLib.instance.api.crateFfiNetworkNetworkGetResolvedTransport();

/// Sets the transport mode for all outgoing traffic. Persist in Dart
/// (settings KV) and re-init relays for the proxy to take effect.
bool networkSetTransportMode({required String mode}) =>
    RustLib.instance.api.crateFfiNetworkNetworkSetTransportMode(mode: mode);

/// Starts Reticulum UDP transport on the specified bind address
String reticulumStartTransport(
        {required String pubkey, required String bindAddr}) =>
    RustLib.instance.api.crateFfiNetworkReticulumStartTransport(
        pubkey: pubkey, bindAddr: bindAddr);

/// Starts Reticulum AutoInterface for peer discovery
String reticulumStartAutoInterface(
        {required String pubkey,
        required bool enabled,
        required int port,
        required BigInt intervalMs}) =>
    RustLib.instance.api.crateFfiNetworkReticulumStartAutoInterface(
        pubkey: pubkey, enabled: enabled, port: port, intervalMs: intervalMs);

/// Starts Reticulum TCP server interface
String reticulumStartTcpServer(
        {required String pubkey,
        required int port,
        required BigInt maxConnections}) =>
    RustLib.instance.api.crateFfiNetworkReticulumStartTcpServer(
        pubkey: pubkey, port: port, maxConnections: maxConnections);

/// Sends a Reticulum packet to the specified destination
bool reticulumSendPacket(
        {required String pubkey,
        required String destAddr,
        required String packetJson}) =>
    RustLib.instance.api.crateFfiNetworkReticulumSendPacket(
        pubkey: pubkey, destAddr: destAddr, packetJson: packetJson);

/// Creates a Reticulum link request to a remote destination
String reticulumRequestLink(
        {required String pubkey, required String destHex}) =>
    RustLib.instance.api
        .crateFfiNetworkReticulumRequestLink(pubkey: pubkey, destHex: destHex);

/// Gets current Reticulum node status
String reticulumGetStatus({required String pubkey}) =>
    RustLib.instance.api.crateFfiNetworkReticulumGetStatus(pubkey: pubkey);

/// Creates a Reticulum address from a public key
String reticulumAddressFromPubkey({required String pubkey}) =>
    RustLib.instance.api
        .crateFfiNetworkReticulumAddressFromPubkey(pubkey: pubkey);

/// Creates a Reticulum address from an app name and aspect
String reticulumAddressFromAspect(
        {required String appName, required String aspect}) =>
    RustLib.instance.api.crateFfiNetworkReticulumAddressFromAspect(
        appName: appName, aspect: aspect);

/// Broadcasts an ANNOUNCE packet for identity discovery
String reticulumCreateAnnounce({required String pubkey, String? aspect}) =>
    RustLib.instance.api
        .crateFfiNetworkReticulumCreateAnnounce(pubkey: pubkey, aspect: aspect);

/// Connects to a Freenet node via WebSocket, replacing any stored client so
/// the connection persists for later `freenet_*` calls.
Future<bool> freenetConnect({required String url, required String authToken}) =>
    RustLib.instance.api
        .crateFfiNetworkFreenetConnect(url: url, authToken: authToken);

/// Fetches contract state from Freenet (via the persistent client).
Future<String> freenetGetContract(
        {required String url,
        required String authToken,
        required String key,
        required bool subscribe}) =>
    RustLib.instance.api.crateFfiNetworkFreenetGetContract(
        url: url, authToken: authToken, key: key, subscribe: subscribe);

/// Publishes contract state to Freenet (via the persistent client).
Future<String> freenetPutContract(
        {required String url,
        required String authToken,
        required String stateJson,
        required bool subscribe}) =>
    RustLib.instance.api.crateFfiNetworkFreenetPutContract(
        url: url,
        authToken: authToken,
        stateJson: stateJson,
        subscribe: subscribe);

/// Subscribes to Freenet contract updates (via the persistent client).
Future<bool> freenetSubscribe(
        {required String url,
        required String authToken,
        required String key,
        String? summaryJson}) =>
    RustLib.instance.api.crateFfiNetworkFreenetSubscribe(
        url: url, authToken: authToken, key: key, summaryJson: summaryJson);

/// Reachability probe against a SAM bridge: connects and completes the SAM
/// handshake, then drops the client. Honest as a probe — the result reports
/// bridge reachability at call time, nothing more. For a durable session use
/// `i2p_start_session`.
bool i2PConnect({required String samHost, required int samPort}) =>
    RustLib.instance.api
        .crateFfiNetworkI2PConnect(samHost: samHost, samPort: samPort);

/// Creates (or re-binds) an I2P SAM session, returning its destination.
///
/// When the endpoint is the managed default bridge the session is created on
/// the persistent `I2P_MANAGER` so it stays alive across calls (stop it with
/// `i2p_stop_session`). Any other bridge cannot persist: SAM session state
/// dies with the control socket, so the surface fails closed instead of
/// returning a destination that stops working on the next call.
String i2PCreateSession(
        {required String samHost,
        required int samPort,
        required String sessionId,
        String? destination}) =>
    RustLib.instance.api.crateFfiNetworkI2PCreateSession(
        samHost: samHost,
        samPort: samPort,
        sessionId: sessionId,
        destination: destination);

/// Generates a new I2P destination via SAM. Pure keygen — the returned
/// destination is real and can later be made persistent by passing it to
/// `i2p_start_session(destination: ...)`.
String i2PGenerateDestination(
        {required String samHost, required int samPort}) =>
    RustLib.instance.api.crateFfiNetworkI2PGenerateDestination(
        samHost: samHost, samPort: samPort);

/// Opens an outbound SAM tunnel to a remote I2P destination.
///
/// Rides the persistent `I2P_MANAGER` session on the managed default bridge so
/// the tunnel is established through a session that survives the call; any
/// other bridge fails closed (one-shot tunnels are dropped with the client and
/// returning `true` would claim a connection that no longer exists).
bool i2PConnectToDestination(
        {required String samHost,
        required int samPort,
        required String sessionId,
        required String destination}) =>
    RustLib.instance.api.crateFfiNetworkI2PConnectToDestination(
        samHost: samHost,
        samPort: samPort,
        sessionId: sessionId,
        destination: destination);

/// Starts the persistent i2p session (SAM). Returns the session destination;
/// persist it and pass it back on later runs to keep a stable address.
String i2PStartSession({String? destination}) => RustLib.instance.api
    .crateFfiNetworkI2PStartSession(destination: destination);

/// Stops the persistent i2p session (if any).
bool i2PStopSession() => RustLib.instance.api.crateFfiNetworkI2PStopSession();

/// `{"running": bool, "destination": string|null}` for the i2p session.
String i2PSessionStatus() =>
    RustLib.instance.api.crateFfiNetworkI2PSessionStatus();

/// Retrieves multi-bearer off-grid mesh connection status.
Future<String> networkGetMultiBearerStatus({required String ownPubkey}) =>
    RustLib.instance.api
        .crateFfiNetworkNetworkGetMultiBearerStatus(ownPubkey: ownPubkey);

/// Process incoming BLE state root beacon and determine if Wi-Fi Direct socket upgrade is needed.
Future<String?> networkProcessBleBeacon(
        {required String beacon,
        required String localRootHex,
        required String ownPubkey}) =>
    RustLib.instance.api.crateFfiNetworkNetworkProcessBleBeacon(
        beacon: beacon, localRootHex: localRootHex, ownPubkey: ownPubkey);

/// Reconciles Prolly Tree root hashes with a remote peer.
Future<String> networkReconcileProllyTree(
        {required String localKvJson, required String remoteRootHash}) =>
    RustLib.instance.api.crateFfiNetworkNetworkReconcileProllyTree(
        localKvJson: localKvJson, remoteRootHash: remoteRootHash);

/// Verifies a zk-SNARK Web-of-Trust moderation proof.
///
/// Legacy 3-arg surface. The security hardening made proof verification
/// prover-bound (`verify_zk_wot_proof` requires the minting prover's pubkey
/// and blacklist root); this surface cannot supply them, so it fails closed
/// with `false` rather than verifying without an identity.
Future<bool> networkVerifyZkWotProof(
        {required String proofJson,
        required String expectedWotRoot,
        required String blacklistedNullifiersJson}) =>
    RustLib.instance.api.crateFfiNetworkNetworkVerifyZkWotProof(
        proofJson: proofJson,
        expectedWotRoot: expectedWotRoot,
        blacklistedNullifiersJson: blacklistedNullifiersJson);

/// Notifies network-core of local IP interface address changes to trigger QUIC connection migration.
bool networkNotifyInterfaceChange({required String newIp}) =>
    RustLib.instance.api
        .crateFfiNetworkNetworkNotifyInterfaceChange(newIp: newIp);

/// Retrieves real-time kernel, hardware crypto, io_uring, and Cuckoo filter diagnostics.
String networkGetSysDiagnostics() =>
    RustLib.instance.api.crateFfiNetworkNetworkGetSysDiagnostics();

/// Stop Reticulum transports: clears the node registry and terminates all
/// background transport threads/interfaces.
bool networkReticulumStop() =>
    RustLib.instance.api.crateFfiNetworkNetworkReticulumStop();

/// Get current Reticulum status from the node registry.
String networkReticulumStatus() =>
    RustLib.instance.api.crateFfiNetworkNetworkReticulumStatus();

/// Announce the active Reticulum destination to known peers. The announce
/// packet carries the node destination so peers build a path to it; with zero
/// known peers nothing can be delivered, and that is reported honestly as an
/// error rather than a silent success.
bool networkReticulumAnnounce({required String pubkey}) => RustLib.instance.api
    .crateFfiNetworkNetworkReticulumAnnounce(pubkey: pubkey);

/// Prune stale Reticulum links; returns count removed.
BigInt networkReticulumPruneStaleLinks() =>
    RustLib.instance.api.crateFfiNetworkNetworkReticulumPruneStaleLinks();

/// Drop expired Reticulum path entries; returns count removed.
BigInt networkReticulumPruneRoutes({required BigInt nowSecs}) =>
    RustLib.instance.api
        .crateFfiNetworkNetworkReticulumPruneRoutes(nowSecs: nowSecs);

/// Proof-of-work node id for a pubkey (hex, `null` when the static nonce fails).
String? networkSkademliaGenerateNodeId(
        {required String pubkey,
        required BigInt staticNonce,
        required BigInt dynamicNonce}) =>
    RustLib.instance.api.crateFfiNetworkNetworkSkademliaGenerateNodeId(
        pubkey: pubkey, staticNonce: staticNonce, dynamicNonce: dynamicNonce);

/// Raw HTTP response: status code plus body bytes.
class HttpResponseDto {
  final int status;
  final Uint8List body;

  const HttpResponseDto({
    required this.status,
    required this.body,
  });

  @override
  int get hashCode => status.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpResponseDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body;
}
