// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client_guard`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NostrEventDto`, `NostrStatusDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Initialize nostr relay client with given relay URLs.
/// Restores relay list from persistence if available.
/// Falls back to default relays if none provided and cache empty.
Future<String> nostrInitRelays({required List<String> relayUrls}) =>
    RustLib.instance.api.crateFfiNostrNostrInitRelays(relayUrls: relayUrls);

/// Get current nostr status (relays, subscriptions).
String nostrStatus() => RustLib.instance.api.crateFfiNostrNostrStatus();

/// Add a relay to the connected relay pool.
Future<bool> nostrAddRelay({required String url}) =>
    RustLib.instance.api.crateFfiNostrNostrAddRelay(url: url);

/// Remove a relay from the relay pool.
Future<bool> nostrRemoveRelay({required String url}) =>
    RustLib.instance.api.crateFfiNostrNostrRemoveRelay(url: url);

/// Subscribe to events matching a filter. Returns subscription ID.
Future<String> nostrSubscribe({required String filterJson}) =>
    RustLib.instance.api.crateFfiNostrNostrSubscribe(filterJson: filterJson);

/// Unsubscribe from a subscription.
Future<bool> nostrUnsubscribe({required String subscriptionId}) =>
    RustLib.instance.api
        .crateFfiNostrNostrUnsubscribe(subscriptionId: subscriptionId);

/// Publish a pre-signed event to all relays. Returns relay count that accepted it.
Future<int> nostrPublishEvent({required String eventJson}) =>
    RustLib.instance.api.crateFfiNostrNostrPublishEvent(eventJson: eventJson);

/// Query events matching a filter. Returns array of event JSON.
Future<String> nostrQueryEvents({required String filterJson}) =>
    RustLib.instance.api.crateFfiNostrNostrQueryEvents(filterJson: filterJson);

/// Get relay connection status for all relays.
Future<String> nostrRelayStatus() =>
    RustLib.instance.api.crateFfiNostrNostrRelayStatus();

/// Publish a custom profile event (kind 30085) to relays.
Future<bool> nostrPublishCustomProfile(
        {required String pubkey, required String profileJson}) =>
    RustLib.instance.api.crateFfiNostrNostrPublishCustomProfile(
        pubkey: pubkey, profileJson: profileJson);
