// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `require_db_rows`, `row_to_item`, `user_names`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NotificationItem`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Fetch unread notifications.
String notificationsFetchUnread(
        {required String userPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsFetchUnread(
        userPubkey: userPubkey, limit: limit);

/// Fetch all notifications with pagination (raw query over the last
/// `limit` rows).
String notificationsFetch(
        {required String userPubkey,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsFetch(
        userPubkey: userPubkey, limit: limit, offset: offset);

/// Mark notification as read.
bool notificationsMarkRead({required String notificationId}) => RustLib
    .instance.api
    .crateFfiNotificationsNotificationsMarkRead(notificationId: notificationId);

/// Mark all notifications as read for a user.
bool notificationsMarkAllRead({required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiNotificationsNotificationsMarkAllRead(userPubkey: userPubkey);

/// Delete a notification.
bool notificationsDelete({required String notificationId}) => RustLib
    .instance.api
    .crateFfiNotificationsNotificationsDelete(notificationId: notificationId);

/// Get unread count.
int notificationsGetUnreadCount({required String userPubkey}) => RustLib
    .instance.api
    .crateFfiNotificationsNotificationsGetUnreadCount(userPubkey: userPubkey);

/// Fetch notifications by type.
String notificationsFetchByType(
        {required String userPubkey,
        required String notificationType,
        required int limit}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsFetchByType(
        userPubkey: userPubkey,
        notificationType: notificationType,
        limit: limit);

/// Fetch mentions.
String notificationsFetchMentions(
        {required String userPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsFetchMentions(
        userPubkey: userPubkey, limit: limit);

/// Fetch likes/reactions.
String notificationsFetchReactions(
        {required String userPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsFetchReactions(
        userPubkey: userPubkey, limit: limit);

/// Fetch replies.
String notificationsFetchReplies(
        {required String userPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsFetchReplies(
        userPubkey: userPubkey, limit: limit);

/// Fetch messages (new DMs).
String notificationsFetchMessages(
        {required String userPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsFetchMessages(
        userPubkey: userPubkey, limit: limit);

/// Fetch follows.
String notificationsFetchFollows(
        {required String userPubkey, required int limit}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsFetchFollows(
        userPubkey: userPubkey, limit: limit);

/// Register the platform push token for the active account.
bool notificationsRegisterPush(
        {required String userPubkey, required String token}) =>
    RustLib.instance.api.crateFfiNotificationsNotificationsRegisterPush(
        userPubkey: userPubkey, token: token);

/// Unregister from push notifications.
bool notificationsUnregisterPush({required String userPubkey}) => RustLib
    .instance.api
    .crateFfiNotificationsNotificationsUnregisterPush(userPubkey: userPubkey);
