// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_report`, `from_state`, `new`, `running`, `state_mut`, `state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BlobFetchDto`, `FountainEncodeDto`, `MoqPublishDto`, `MoqSubscribeDto`, `P2pState`, `SwarmHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`

/// Start advertising this device's chunk server over mDNS. `pubkey` may be
/// empty, in which case the unlocked signer's pubkey is used. `quic_port` is
/// advertised in TXT records if provided.
bool p2PMdnsAdvertiseStart(
        {required String pubkey, required int port, int? quicPort}) =>
    RustLib.instance.api.crateFfiP2PP2PMdnsAdvertiseStart(
        pubkey: pubkey, port: port, quicPort: quicPort);

/// Stop advertising (and drop the mDNS daemon).
bool p2PMdnsAdvertiseStop() =>
    RustLib.instance.api.crateFfiP2PP2PMdnsAdvertiseStop();

/// Start browsing the local subnet for `_soshal._tcp` services (idempotent).
bool p2PMdnsBrowseStart() =>
    RustLib.instance.api.crateFfiP2PP2PMdnsBrowseStart();

/// Drain pending mDNS discovery results as a JSON list of peers.
///
/// Contact-graph gating: an advertiser is only accepted when we already know
/// its pubkey (a stored user/profile row or an entry in our own kind-3
/// contact list). Without this, ANY LAN device running the app — or a hostile
/// advertiser spoofing `_soshal._tcp` — becomes a swarm peer.
List<P2pPeerDto> p2PMdnsBrowseDrain() =>
    RustLib.instance.api.crateFfiP2PP2PMdnsBrowseDrain();

/// Stop browsing (and drop the mDNS daemon).
bool p2PMdnsBrowseStop() => RustLib.instance.api.crateFfiP2PP2PMdnsBrowseStop();

/// Start the HMAC-authenticated LAN chunk server on an ephemeral port.
/// The MAC key is derived from the unlocked signer — never crosses FFI.
/// `store_root` may be empty to serve the default chunk store.
int p2PLanServerStart({required String storeRoot}) =>
    RustLib.instance.api.crateFfiP2PP2PLanServerStart(storeRoot: storeRoot);

/// Port of the running LAN chunk server, if any.
int p2PLanServerPort() => RustLib.instance.api.crateFfiP2PP2PLanServerPort();

/// Stop the LAN chunk server.
bool p2PLanServerStop() => RustLib.instance.api.crateFfiP2PP2PLanServerStop();

/// Start the QUIC stream media server on an ephemeral port. Serves the same
/// HMAC-authenticated chunk CAS as the TCP LAN server, but over QUIC
/// bi-streams (connection migration across Wi-Fi/cellular, multiplexing).
/// `store_root` may be empty to serve the default chunk store.
int p2PQuicServerStart({required String storeRoot}) =>
    RustLib.instance.api.crateFfiP2PP2PQuicServerStart(storeRoot: storeRoot);

/// Port of the running QUIC stream server, if any.
int p2PQuicServerPort() => RustLib.instance.api.crateFfiP2PP2PQuicServerPort();

/// Stop the QUIC stream server.
bool p2PQuicServerStop() => RustLib.instance.api.crateFfiP2PP2PQuicServerStop();

/// Fetch one chunk range from a peer over a QUIC stream (blob-hash or
/// chunk-hash mode, same semantics as the TCP LAN fetch) and verify its
/// BLAKE3 hash before returning. `addr` must be a private IP.
Future<Uint8List> p2PQuicFetchChunk(
        {required String addr,
        required String hash,
        required BigInt offset,
        required BigInt length}) =>
    RustLib.instance.api.crateFfiP2PP2PQuicFetchChunk(
        addr: addr, hash: hash, offset: offset, length: length);

/// Encode a MoQ group (JSON `MoqGroup`) into the on-stream binary framing.
Uint8List p2PMoqEncodeGroup({required String groupJson}) =>
    RustLib.instance.api.crateFfiP2PP2PMoqEncodeGroup(groupJson: groupJson);

/// Decode a MoQ group from the on-stream binary framing back to JSON
/// `MoQGroup`. Bounds-checked against hostile input.
String p2PMoqDecodeGroup({required List<int> bytes}) =>
    RustLib.instance.api.crateFfiP2PP2PMoqDecodeGroup(bytes: bytes);

/// Publish one encoded MoQ group into the live registry under `stream_id`.
/// Bytes are opaque to the transport; the caller encodes with
/// `p2p_moq_encode_group`. Returns JSON `{"status","stream_id","groups"}`.
String p2PMoqPublishGroup(
        {required String streamId, required List<int> encoded}) =>
    RustLib.instance.api
        .crateFfiP2PP2PMoqPublishGroup(streamId: streamId, encoded: encoded);

/// Subscribe to a live MoQ stream over QUIC for `window_ms`. Returns JSON
/// `{"groups":[<hex-encoded group frames>...]}` — one entry per group frame
/// sent by the peer (buffered replay, then live follow until idle/window end).
Future<String> p2PMoqSubscribeFetch(
        {required String addr,
        required String streamId,
        required BigInt windowMs}) =>
    RustLib.instance.api.crateFfiP2PP2PMoqSubscribeFetch(
        addr: addr, streamId: streamId, windowMs: windowMs);

/// Hash-only blob fetch from a single LAN peer: crawl the manifest over QUIC
/// (fallback TCP), then pull every chunk body (QUIC preferred, TCP fallback),
/// verify BLAKE3 per chunk + whole blob, absorb into the CAS, and write the
/// file. Returns JSON `{"success":true,"path","bytes"}`.
/// `ip` is a private-address string; `tcp_port` the LAN server port, and
/// `quic_port` the peer's QUIC stream port when advertised (else empty/None).
Future<String> p2PFetchBlobFromPeer(
        {required String blobHash,
        required String ip,
        required int tcpPort,
        int? quicPort,
        required String outPath}) =>
    RustLib.instance.api.crateFfiP2PP2PFetchBlobFromPeer(
        blobHash: blobHash,
        ip: ip,
        tcpPort: tcpPort,
        quicPort: quicPort,
        outPath: outPath);

/// Kick off a swarm download of `manifest_json` from `peers_json` (a list of
/// `"ip:port"` strings) into `out_path`, then return the download id.
/// `quic_ports_json` is a parallel list of optional QUIC ports (null if not advertised).
/// Worker count is capped by the power scheduler: paused mode serializes
/// (1 worker) so background battery downloads can't ramp the radio.
String p2PSwarmDownload(
        {required String manifestJson,
        required String peersJson,
        required String quicPortsJson,
        required String outPath,
        required BigInt maxParallel}) =>
    RustLib.instance.api.crateFfiP2PP2PSwarmDownload(
        manifestJson: manifestJson,
        peersJson: peersJson,
        quicPortsJson: quicPortsJson,
        outPath: outPath,
        maxParallel: maxParallel);

/// Poll a swarm download: `done` once the thread finished (report attached),
/// `running` otherwise. The finished handle is removed from the registry.
P2pSwarmStatusDto p2PSwarmPoll({required String id}) =>
    RustLib.instance.api.crateFfiP2PP2PSwarmPoll(id: id);

/// Cancel a swarm download: sets the abort token so the worker stops
/// fetching and releases the mmap; the thread is detached, not joined.
bool p2PSwarmCancel({required String id}) =>
    RustLib.instance.api.crateFfiP2PP2PSwarmCancel(id: id);

/// Push OS power/connectivity state into the seeding scheduler. Returns the
/// resulting mode snapshot. Call this whenever the OS battery or network
/// status changes (Dart polls battery_plus / connectivity_plus).
P2pPowerDto p2PPowerUpdate(
        {required bool charging,
        required int batteryPercent,
        required bool cellular,
        required bool lowPowerMode}) =>
    RustLib.instance.api.crateFfiP2PP2PPowerUpdate(
        charging: charging,
        batteryPercent: batteryPercent,
        cellular: cellular,
        lowPowerMode: lowPowerMode);

/// Current seeding mode snapshot.
P2pPowerDto p2PPowerMode() => RustLib.instance.api.crateFfiP2PP2PPowerMode();

/// Tear down all P2P runtime state (mDNS, LAN server, in-flight downloads).
bool p2PStopAll() => RustLib.instance.api.crateFfiP2PP2PStopAll();

/// Encodes raw payload into rateless RaptorQ Fountain code packets.
String p2PEncodeFountainPayload(
        {required List<int> data, required double redundancyRatio}) =>
    RustLib.instance.api.crateFfiP2PP2PEncodeFountainPayload(
        data: data, redundancyRatio: redundancyRatio);

/// Decodes received Fountain code packets back into original payload.
Uint8List p2PDecodeFountainPayload(
        {required String manifestJson, required String packetsB64Json}) =>
    RustLib.instance.api.crateFfiP2PP2PDecodeFountainPayload(
        manifestJson: manifestJson, packetsB64Json: packetsB64Json);

/// A peer discovered on the local subnet.
class P2pPeerDto {
  final String pubkey;
  final String ip;
  final int port;
  final int? quicPort;

  const P2pPeerDto({
    required this.pubkey,
    required this.ip,
    required this.port,
    this.quicPort,
  });

  @override
  int get hashCode =>
      pubkey.hashCode ^ ip.hashCode ^ port.hashCode ^ quicPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P2pPeerDto &&
          runtimeType == other.runtimeType &&
          pubkey == other.pubkey &&
          ip == other.ip &&
          port == other.port &&
          quicPort == other.quicPort;
}

/// Snapshot of the seeding scheduler state (what Dart pushes + what it reads).
class P2pPowerDto {
  final String mode;
  final bool paused;
  final BigInt maxParallelUploads;
  final BigInt uploadBudgetBytesPerSec;

  const P2pPowerDto({
    required this.mode,
    required this.paused,
    required this.maxParallelUploads,
    required this.uploadBudgetBytesPerSec,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      paused.hashCode ^
      maxParallelUploads.hashCode ^
      uploadBudgetBytesPerSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P2pPowerDto &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          paused == other.paused &&
          maxParallelUploads == other.maxParallelUploads &&
          uploadBudgetBytesPerSec == other.uploadBudgetBytesPerSec;
}

/// Progress of an in-flight swarm download.
class P2pSwarmStatusDto {
  final String state;
  final BigInt verifiedChunks;
  final BigInt bytesDownloaded;
  final BigInt failures;
  final List<String> failedHashes;

  const P2pSwarmStatusDto({
    required this.state,
    required this.verifiedChunks,
    required this.bytesDownloaded,
    required this.failures,
    required this.failedHashes,
  });

  static Future<P2pSwarmStatusDto> default_() =>
      RustLib.instance.api.crateFfiP2PP2PSwarmStatusDtoDefault();

  @override
  int get hashCode =>
      state.hashCode ^
      verifiedChunks.hashCode ^
      bytesDownloaded.hashCode ^
      failures.hashCode ^
      failedHashes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P2pSwarmStatusDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          verifiedChunks == other.verifiedChunks &&
          bytesDownloaded == other.bytesDownloaded &&
          failures == other.failures &&
          failedHashes == other.failedHashes;
}
