// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ashpd_location`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Host platform name: "android", "linux", or "other".
String permissionsPlatformCurrent() =>
    RustLib.instance.api.crateFfiPermissionsPermissionsPlatformCurrent();

/// Camera + microphone both granted.
bool permissionsCameraMicGranted() =>
    RustLib.instance.api.crateFfiPermissionsPermissionsCameraMicGranted();

/// Fire the camera + microphone permission dialog (grouped on Android 12+).
/// Returns false when unsupported; result is polled via `*_granted`.
bool permissionsCameraMicRequest() =>
    RustLib.instance.api.crateFfiPermissionsPermissionsCameraMicRequest();

/// Both denied with "don't ask again" (no rationale would be shown).
bool permissionsCameraMicPermanentlyDenied() => RustLib.instance.api
    .crateFfiPermissionsPermissionsCameraMicPermanentlyDenied();

/// Open the OS app-settings page (Android).
bool permissionsOpenSettings() =>
    RustLib.instance.api.crateFfiPermissionsPermissionsOpenSettings();

/// Fine location granted.
bool permissionsLocationGranted() =>
    RustLib.instance.api.crateFfiPermissionsPermissionsLocationGranted();

/// Fire the location permission dialog. Result polled via `*_granted`.
bool permissionsLocationRequest() =>
    RustLib.instance.api.crateFfiPermissionsPermissionsLocationRequest();

/// Any location provider (GPS or network) enabled.
bool permissionsLocationEnabled() =>
    RustLib.instance.api.crateFfiPermissionsPermissionsLocationEnabled();

/// XDG Desktop Portal location fix (Linux only; Err elsewhere).
Future<LocationFixDto?> permissionsLocationPortalFix() =>
    RustLib.instance.api.crateFfiPermissionsPermissionsLocationPortalFix();

/// A location fix: coordinates or an honest failure reason.
class LocationFixDto {
  final double latitude;
  final double longitude;

  const LocationFixDto({
    required this.latitude,
    required this.longitude,
  });

  @override
  int get hashCode => latitude.hashCode ^ longitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocationFixDto &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude;
}
