// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_pin_with_lockout`, `now_ms`, `with_repo`

/// Set (or reset) the lock PIN. Must be 4-12 digits.
bool pinSet({required String pin}) =>
    RustLib.instance.api.crateFfiPinPinSet(pin: pin);

/// Whether a PIN is configured.
bool pinHas() => RustLib.instance.api.crateFfiPinPinHas();

/// Verify the PIN with full lockout enforcement. Returns Ok(true) on a
/// correct PIN, Ok(false) on wrong PIN / lockout / error.
bool pinVerify({required String pin}) =>
    RustLib.instance.api.crateFfiPinPinVerify(pin: pin);

/// Clear the PIN after verifying the current one.
bool pinClear({required String pin}) =>
    RustLib.instance.api.crateFfiPinPinClear(pin: pin);

/// Lockout state snapshot for the lock screen UI.
String pinLockoutState() => RustLib.instance.api.crateFfiPinPinLockoutState();
