// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `linux_sample`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// One-shot OS power/connectivity sample.
Future<PowerStateDto> powerSampleOsState() =>
    RustLib.instance.api.crateFfiPowerPowerSampleOsState();

/// OS power/connectivity facts consumed by the seeding scheduler.
class PowerStateDto {
  final bool charging;
  final int batteryPercent;
  final bool cellular;
  final bool lowPowerMode;

  const PowerStateDto({
    required this.charging,
    required this.batteryPercent,
    required this.cellular,
    required this.lowPowerMode,
  });

  @override
  int get hashCode =>
      charging.hashCode ^
      batteryPercent.hashCode ^
      cellular.hashCode ^
      lowPowerMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PowerStateDto &&
          runtimeType == other.runtimeType &&
          charging == other.charging &&
          batteryPercent == other.batteryPercent &&
          cellular == other.cellular &&
          lowPowerMode == other.lowPowerMode;
}
