// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// ML-KEM-768 keypair generation.
/// Returns JSON `{"pk": "<hex>", "sk": "<hex>"}`.
String pqcKemKeygen() => RustLib.instance.api.crateFfiPqcPqcKemKeygen();

/// ML-KEM-768 encapsulation to a recipient public key.
/// Returns JSON `{"ct": "<hex>", "ss": "<hex>"}`.
String pqcKemEncaps({required String recipientPkHex}) => RustLib.instance.api
    .crateFfiPqcPqcKemEncaps(recipientPkHex: recipientPkHex);

/// ML-KEM-768 decapsulation with the secret key.
/// Returns the 32-byte shared secret as hex.
String pqcKemDecaps({required String ciphertextHex, required String skHex}) =>
    RustLib.instance.api
        .crateFfiPqcPqcKemDecaps(ciphertextHex: ciphertextHex, skHex: skHex);

/// ML-DSA-65 keypair generation.
/// Returns JSON `{"sk": "<hex>", "vk": "<hex>"}`.
String pqcDsaKeygen() => RustLib.instance.api.crateFfiPqcPqcDsaKeygen();

/// ML-DSA-65 signing of `message_hex` with the secret key.
/// Returns the signature as hex.
String pqcDsaSign({required String messageHex, required String skHex}) =>
    RustLib.instance.api
        .crateFfiPqcPqcDsaSign(messageHex: messageHex, skHex: skHex);

/// ML-DSA-65 verification of `sig_hex` over `message_hex` with the public key.
/// Returns JSON `{"valid": bool}`.
String pqcDsaVerify(
        {required String sigHex,
        required String messageHex,
        required String vkHex}) =>
    RustLib.instance.api.crateFfiPqcPqcDsaVerify(
        sigHex: sigHex, messageHex: messageHex, vkHex: vkHex);

/// Hybrid X25519 + ML-KEM-768 sealed blob: KEM encapsulate + ChaCha20-Poly1305.
/// Returns JSON `{"ct": "<hex>", "nonce": "<hex>", "b64": "<base64>"}`.
String pqcHybridSeal(
        {required String payloadHex, required String recipientPkHex}) =>
    RustLib.instance.api.crateFfiPqcPqcHybridSeal(
        payloadHex: payloadHex, recipientPkHex: recipientPkHex);

/// Opens a blob produced by `pqc_hybrid_seal`. Returns plaintext as hex.
String pqcHybridUnseal(
        {required String ctHex,
        required String nonceHex,
        required String b64,
        required String skHex}) =>
    RustLib.instance.api.crateFfiPqcPqcHybridUnseal(
        ctHex: ctHex, nonceHex: nonceHex, b64: b64, skHex: skHex);

/// HKDF-SHA256 (RFC 5869) over hex inputs. Returns `len` derived bytes as hex.
String pqcHkdfSha256(
        {required String ikmHex,
        required String saltHex,
        required String infoHex,
        required int len}) =>
    RustLib.instance.api.crateFfiPqcPqcHkdfSha256(
        ikmHex: ikmHex, saltHex: saltHex, infoHex: infoHex, len: len);
