// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `infer_mime_from_path`, `protocol_fetch_from_blossom`, `protocol_handle_avatar`, `protocol_handle_cache`, `protocol_handle_media`, `protocol_handle_relay`, `protocol_load_from_cache`, `protocol_metadata_avatar`, `protocol_metadata_media`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProtocolResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Handle app:// protocol requests
Future<Uint8List> protocolHandleRequest(
        {required String scheme, required String host, required String path}) =>
    RustLib.instance.api.crateFfiProtocolHandlerProtocolHandleRequest(
        scheme: scheme, host: host, path: path);

/// Get response metadata for a resource
Future<String> protocolGetMetadata(
        {required String scheme, required String host, required String path}) =>
    RustLib.instance.api.crateFfiProtocolHandlerProtocolGetMetadata(
        scheme: scheme, host: host, path: path);
