// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Registers a shared pixel buffer memory callback for Flutter Impeller rasterizer.
Future<ImpellerFrameBufferInfo> rasterAllocateFrameBuffer(
        {required int width, required int height}) =>
    RustLib.instance.api
        .crateFfiRasterRasterAllocateFrameBuffer(width: width, height: height);

/// Pushes frame render signal directly to Impeller raster pipeline.
Future<bool> rasterSignalImpellerFrameReady(
        {required PlatformInt64 textureId, required BigInt frameTimestampNs}) =>
    RustLib.instance.api.crateFfiRasterRasterSignalImpellerFrameReady(
        textureId: textureId, frameTimestampNs: frameTimestampNs);

/// Frame metadata for decoded video/media buffer.
class ImpellerFrameBufferInfo {
  final int width;
  final int height;
  final int stride;
  final String pixelFormat;
  final BigInt bufferPtrAddr;

  const ImpellerFrameBufferInfo({
    required this.width,
    required this.height,
    required this.stride,
    required this.pixelFormat,
    required this.bufferPtrAddr,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      stride.hashCode ^
      pixelFormat.hashCode ^
      bufferPtrAddr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImpellerFrameBufferInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          stride == other.stride &&
          pixelFormat == other.pixelFormat &&
          bufferPtrAddr == other.bufferPtrAddr;
}
