// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a new WGPU compute session for rendering offscreen mesh layout
String renderCreateSession({required int width, required int height}) =>
    RustLib.instance.api
        .crateFfiRenderRenderCreateSession(width: width, height: height);

/// Step WGPU force-directed graph physics & generate offscreen RGBA pixel frame
Uint8List renderComputeMeshFrame(
        {required PlatformInt64 sessionId,
        required String nodesJson,
        required double deltaTime}) =>
    RustLib.instance.api.crateFfiRenderRenderComputeMeshFrame(
        sessionId: sessionId, nodesJson: nodesJson, deltaTime: deltaTime);
