// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hashtags_to_json`

/// Create a scheduled post draft. `scheduled_at` is a unix timestamp in the
/// future; `publish_at` (unix) marks when sync should broadcast it.
String scheduledCreate(
        {required String pubkey,
        required String content,
        required PlatformInt64 scheduledAt,
        required List<String> hashtags}) =>
    RustLib.instance.api.crateFfiScheduledScheduledCreate(
        pubkey: pubkey,
        content: content,
        scheduledAt: scheduledAt,
        hashtags: hashtags);

/// List scheduled drafts for a pubkey, soonest first. Returns JSON array of
/// post rows.
String scheduledList({required String pubkey}) =>
    RustLib.instance.api.crateFfiScheduledScheduledList(pubkey: pubkey);

/// Delete a scheduled draft (soft delete).
bool scheduledDelete({required String id}) =>
    RustLib.instance.api.crateFfiScheduledScheduledDelete(id: id);
