// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run_search`, `truncate_preview`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SearchResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Search posts by content (kind 1).
String searchPosts({required String query, required int limit}) =>
    RustLib.instance.api.crateFfiSearchSearchPosts(query: query, limit: limit);

/// Search profiles by name/about (kind 0).
String searchProfiles({required String query, required int limit}) =>
    RustLib.instance.api
        .crateFfiSearchSearchProfiles(query: query, limit: limit);

/// Search hashtags (trending list fallback if no hash-index rows yet).
List<String> searchHashtags({required String query, required int limit}) =>
    RustLib.instance.api
        .crateFfiSearchSearchHashtags(query: query, limit: limit);

/// Search mentions (profiles matching the query prefix).
String searchMentions({required String query, required int limit}) =>
    RustLib.instance.api
        .crateFfiSearchSearchMentions(query: query, limit: limit);

/// Global search across all indexed kinds.
String searchGlobal({required String query, required int limit}) =>
    RustLib.instance.api.crateFfiSearchSearchGlobal(query: query, limit: limit);

/// Remote NIP-50 search: query relays for matching text notes. Returns a
/// JSON array of {id, pubkey, content, created_at} for verified events.
Future<String> searchRemoteGlobal(
        {required String query,
        required BigInt limit,
        required String relaysJson}) =>
    RustLib.instance.api.crateFfiSearchSearchRemoteGlobal(
        query: query, limit: limit, relaysJson: relaysJson);

/// Get trending hashtags from the hashtag index.
List<String> searchTrendingHashtags({required int limit}) =>
    RustLib.instance.api.crateFfiSearchSearchTrendingHashtags(limit: limit);

/// Get trending profiles (most followers in local graph).
String searchTrendingProfiles({required int limit}) =>
    RustLib.instance.api.crateFfiSearchSearchTrendingProfiles(limit: limit);

/// Index a post (or any kind) into the FTS search table.
bool searchIndexPost(
        {required String eventId,
        required String pubkey,
        required String content,
        required PlatformInt64 kind}) =>
    RustLib.instance.api.crateFfiSearchSearchIndexPost(
        eventId: eventId, pubkey: pubkey, content: content, kind: kind);

/// Index a profile into the FTS search table (kind 0 row).
bool searchIndexProfile(
        {required String pubkey,
        required String name,
        required String about}) =>
    RustLib.instance.api.crateFfiSearchSearchIndexProfile(
        pubkey: pubkey, name: name, about: about);

/// Remove an entry from the search index.
bool searchRemoveIndexed({required String id}) =>
    RustLib.instance.api.crateFfiSearchSearchRemoveIndexed(id: id);
