// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_idle_timeout`, `load_or_create_session_key`, `load_session_from_disk`, `lock_session`, `persist_session`, `random_suffix`, `session_key_path`, `session_sig_valid`, `sign_session`, `validate_npub`, `validate_path_security`, `validate_pubkey_hex`, `validated_session_path_hardened`, `validated_session_path`, `write_session_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SESSION`, `SessionAccount`, `SessionData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `fmt`, `fmt`, `initialize`

/// Load session from file
String sessionLoad({required String dbPath}) =>
    RustLib.instance.api.crateFfiSessionSessionLoad(dbPath: dbPath);

/// Save session to file
bool sessionSave({required String dbPath, required String sessionData}) =>
    RustLib.instance.api
        .crateFfiSessionSessionSave(dbPath: dbPath, sessionData: sessionData);

/// Add account to session
bool sessionAddAccount(
        {required String pubkey,
        required String npub,
        required String relaysJson}) =>
    RustLib.instance.api.crateFfiSessionSessionAddAccount(
        pubkey: pubkey, npub: npub, relaysJson: relaysJson);

/// Switch to an account
bool sessionSwitchAccount({required String pubkey}) =>
    RustLib.instance.api.crateFfiSessionSessionSwitchAccount(pubkey: pubkey);

/// Remove an account from the session, persisting the change to disk.
/// If the removed account was active, the active account is reassigned to the
/// first remaining account (or cleared if none remain).
bool sessionRemoveAccount({required String pubkey}) =>
    RustLib.instance.api.crateFfiSessionSessionRemoveAccount(pubkey: pubkey);

/// Get active account
String sessionGetActive() =>
    RustLib.instance.api.crateFfiSessionSessionGetActive();

/// List all accounts
String sessionListAccounts() =>
    RustLib.instance.api.crateFfiSessionSessionListAccounts();

/// Reset in-memory session state (unload).
bool sessionClear() => RustLib.instance.api.crateFfiSessionSessionClear();

/// Register (or clear, when empty) the push token for the active account.
/// Persists to session.json via the current DB path.
///
/// Save-first: the in-memory session is only updated after a successful disk
/// write.  If `session_save` fails the caller receives the error and the
/// in-memory state is unchanged.
bool sessionRegisterPushToken({required String token}) =>
    RustLib.instance.api.crateFfiSessionSessionRegisterPushToken(token: token);
