// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `keychain_service`, `keychain_user`, `lan_key`, `sign_builder`

/// Unlock the signer with an nsec (or hex secret key). Accepts BOTH bech32
/// `nsec1...` and 64-char hex input via `Keys::parse`.
///
/// Returns the hex public key of the unlocked identity.
String signerUnlock({required String secret}) =>
    RustLib.instance.api.crateFfiSignerSignerUnlock(secret: secret);

/// Lock the signer: drop the in-memory key (zeroized on drop).
bool signerLock() => RustLib.instance.api.crateFfiSignerSignerLock();

/// Whether the signer currently holds an unlocked identity.
bool signerIsLocked() => RustLib.instance.api.crateFfiSignerSignerIsLocked();

/// Hex public key of the unlocked identity, or an error if locked.
String signerPubkey() => RustLib.instance.api.crateFfiSignerSignerPubkey();

/// Persist the unlocked secret key to the OS keychain (desktop keyring).
/// Only called explicitly after the user opts into "remember this device".
bool signerSaveToKeyring({required String pubkey}) =>
    RustLib.instance.api.crateFfiSignerSignerSaveToKeyring(pubkey: pubkey);

/// Unlock the signer from the OS keychain for the given pubkey.
bool signerUnlockFromKeyring({required String pubkey}) =>
    RustLib.instance.api.crateFfiSignerSignerUnlockFromKeyring(pubkey: pubkey);

/// Remove the stored secret key for an account from the OS keychain.
bool signerRemoveFromKeyring({required String pubkey}) =>
    RustLib.instance.api.crateFfiSignerSignerRemoveFromKeyring(pubkey: pubkey);

/// Sign a Schnorr message digest (32 bytes, hex) with the unlocked key.
/// Returns the 64-byte signature as hex.
String signerSchnorrSign({required String messageHex}) => RustLib.instance.api
    .crateFfiSignerSignerSchnorrSign(messageHex: messageHex);

/// Sign a text message: hashes with SHA-256 then Schnorr-signs the digest in Rust.
String signerSignText({required String message}) =>
    RustLib.instance.api.crateFfiSignerSignerSignText(message: message);

/// Sign an unsigned event (NIP-59 style JSON: `pubkey`, `created_at`,
/// `kind`, `tags`, `content`; `id` optional) with the unlocked key.
/// Returns the fully signed event JSON including `id` and `sig`.
String signerSignUnsigned({required String eventJson}) =>
    RustLib.instance.api.crateFfiSignerSignerSignUnsigned(eventJson: eventJson);

/// NIP-44 v2 encrypt plaintext to `recipient_pubkey` using the unlocked key.
/// Returns the wire-format payload (base64: `2 ‖ nonce ‖ ct ‖ mac`).
String signerNip44Encrypt(
        {required String plaintext, required String recipientPubkey}) =>
    RustLib.instance.api.crateFfiSignerSignerNip44Encrypt(
        plaintext: plaintext, recipientPubkey: recipientPubkey);

/// NIP-44 v2 decrypt a payload from `sender_pubkey` using the unlocked key.
String signerNip44Decrypt(
        {required String payload, required String senderPubkey}) =>
    RustLib.instance.api.crateFfiSignerSignerNip44Decrypt(
        payload: payload, senderPubkey: senderPubkey);
