// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Waveform peaks (normalized 0..1) for an audio file or voice-note stream.
Float32List storageGetAudioPeaks({required String path}) =>
    RustLib.instance.api.crateFfiStorageStorageGetAudioPeaks(path: path);

/// Encode mono i16 PCM (48 kHz) into a framed Opus voice-note stream.
Uint8List storageEncodeVoicePcm({required List<int> pcm}) =>
    RustLib.instance.api.crateFfiStorageStorageEncodeVoicePcm(pcm: pcm);

/// Decode a framed Opus voice-note stream to mono i16 PCM.
Int16List storageDecodeVoiceStream({required List<int> payload}) =>
    RustLib.instance.api
        .crateFfiStorageStorageDecodeVoiceStream(payload: payload);

/// Duration in seconds of a voice-note stream.
double storageVoiceDurationSecs({required List<int> payload}) =>
    RustLib.instance.api
        .crateFfiStorageStorageVoiceDurationSecs(payload: payload);

/// Detect and return active storage I/O engine mode (IoUringKernelRing, MemmapZeroCopy, StandardTokioFs).
String storageGetIoEngineMode() =>
    RustLib.instance.api.crateFfiStorageStorageGetIoEngineMode();
