// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `story_from_value`, `stream_from_value`, `tag_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StoryInfo`, `StreamInfo`, `VIDEO_SERVER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `fmt`, `fmt`, `initialize`

/// Start the local Rust video streaming HTTP micro-server bound to 127.0.0.1:0.
Future<int> streamingStartLocalServer() =>
    RustLib.instance.api.crateFfiStreamingStreamingStartLocalServer();

/// Register a video asset with the local video micro-server and return its localhost URL.
String streamingGetVideoUrl(
        {required String videoId, required String sourcePath}) =>
    RustLib.instance.api.crateFfiStreamingStreamingGetVideoUrl(
        videoId: videoId, sourcePath: sourcePath);

/// Fetch live streams (all locally known + optionally filter to `live`).
String streamingFetchLive({required int limit}) =>
    RustLib.instance.api.crateFfiStreamingStreamingFetchLive(limit: limit);

/// Fetch live streams from followed users (contact graph join).
String streamingFetchFollowedLive({required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiStreamingStreamingFetchFollowedLive(userPubkey: userPubkey);

/// Start a live stream announcement (kind 30311 with `status` = live).
/// Signs and stores locally; returns the signed event JSON.
String streamingStartLive(
        {required String broadcasterPubkey,
        required String title,
        required String description,
        required String streamUrl}) =>
    RustLib.instance.api.crateFfiStreamingStreamingStartLive(
        broadcasterPubkey: broadcasterPubkey,
        title: title,
        description: description,
        streamUrl: streamUrl);

/// End a live stream: replace the local `status` tag with `ended`.
bool streamingEndLive(
        {required String streamId, required String broadcasterPubkey}) =>
    RustLib.instance.api.crateFfiStreamingStreamingEndLive(
        streamId: streamId, broadcasterPubkey: broadcasterPubkey);

/// Post a story (kind 30078, d = `soshal_story`, expiration tag 24h unless
/// overridden). Signs and stores locally.
String streamingPostStory(
        {required String authorPubkey,
        required String content,
        required String imagesJson,
        required int expiresInHours}) =>
    RustLib.instance.api.crateFfiStreamingStreamingPostStory(
        authorPubkey: authorPubkey,
        content: content,
        imagesJson: imagesJson,
        expiresInHours: expiresInHours);

/// Fetch a user's stories (unexpired only).
String streamingFetchStories({required String userPubkey}) =>
    RustLib.instance.api
        .crateFfiStreamingStreamingFetchStories(userPubkey: userPubkey);

/// Fetch stories from all accounts the user follows (via contact lists).
String streamingFetchFollowedStories({required String viewerPubkey}) => RustLib
    .instance.api
    .crateFfiStreamingStreamingFetchFollowedStories(viewerPubkey: viewerPubkey);

/// Mark a story viewed (post_views is keyed (pubkey, post_id)).
bool streamingMarkStoryViewed(
        {required String storyId, required String viewerPubkey}) =>
    RustLib.instance.api.crateFfiStreamingStreamingMarkStoryViewed(
        storyId: storyId, viewerPubkey: viewerPubkey);

/// Record a story reaction (emoji).
bool streamingStoryReact(
        {required String storyId,
        required String pubkey,
        required String emoji}) =>
    RustLib.instance.api.crateFfiStreamingStreamingStoryReact(
        storyId: storyId, pubkey: pubkey, emoji: emoji);

/// Create a Media over QUIC (MoQ) object for low-latency P2P publishing.
String streamingMoqPublishObject(
        {required String streamId,
        required String publisherPubkey,
        required int trackId,
        required bool isKeyframe,
        required String payloadHex}) =>
    RustLib.instance.api.crateFfiStreamingStreamingMoqPublishObject(
        streamId: streamId,
        publisherPubkey: publisherPubkey,
        trackId: trackId,
        isKeyframe: isKeyframe,
        payloadHex: payloadHex);

/// Check live stream availability and report transport status. Subscription
/// itself happens per-peer via `p2p_moq_subscribe_fetch` (QUIC stream fetch).
String streamingMoqSubscribeStream(
        {required String streamId, required String subscriberPubkey}) =>
    RustLib.instance.api.crateFfiStreamingStreamingMoqSubscribeStream(
        streamId: streamId, subscriberPubkey: subscriberPubkey);
