// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `publish_or_enqueue`, `sink_guard`, `update_json`

/// Subscribe to live sync updates. Each item is a JSON object tagged by
/// `t`: `feed`, `dm`, `reaction`, or `profile`. The `StreamSink` parameter
/// makes this a Rust→Dart stream: Dart subscribes via `syncEvents()`.
Stream<String> syncEvents() => RustLib.instance.api.crateFfiSyncSyncEvents();

/// Start the background sync engine with the given relay URLs (JSON array).
/// The engine runs on its own OS thread + tokio runtime, so relay
/// connections survive app backgrounding; updates flow to `sync_events`.
Future<String> syncStart({required String relaysJson}) =>
    RustLib.instance.api.crateFfiSyncSyncStart(relaysJson: relaysJson);

/// Stop the background sync engine (disconnects relays; closes its runtime).
Future<bool> syncStop() => RustLib.instance.api.crateFfiSyncSyncStop();

/// Whether an engine instance is currently running.
bool syncRunning() => RustLib.instance.api.crateFfiSyncSyncRunning();

/// Enqueue an action (post, comment, media upload) to the persistent offline outbox queue.
String syncEnqueueOutbox(
        {required String actionType,
        required String payloadJson,
        String? mediaPath}) =>
    RustLib.instance.api.crateFfiSyncSyncEnqueueOutbox(
        actionType: actionType, payloadJson: payloadJson, mediaPath: mediaPath);

/// Get outbox summary counters (pending, failed, total).
String syncGetOutboxSummary() =>
    RustLib.instance.api.crateFfiSyncSyncGetOutboxSummary();

/// Triggers CRDT epoch garbage collection across active peer vector clocks to prune tombstones.
String syncRunEpochGarbageCollection(
        {required String domain,
        required String peerVectorClocksJson,
        required BigInt gcThresholdSecs}) =>
    RustLib.instance.api.crateFfiSyncSyncRunEpochGarbageCollection(
        domain: domain,
        peerVectorClocksJson: peerVectorClocksJson,
        gcThresholdSecs: gcThresholdSecs);
