// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`

/// Open (or create) the flight recorder at `path` with `capacity_mb` MiB of
/// ring space. Safe to call repeatedly; reopens the same file.
void telemetryInit({required String path, required int capacityMb}) =>
    RustLib.instance.api
        .crateFfiTelemetryTelemetryInit(path: path, capacityMb: capacityMb);

/// Append a record. kind: 1=State 2=Ipc 3=Network 4=Ffi 5=App 6=Crash.
void telemetryRecord({required int kind, required String msg}) =>
    RustLib.instance.api.crateFfiTelemetryTelemetryRecord(kind: kind, msg: msg);

/// Seal the recorder with a crash reason; blocks further writes.
void telemetryMarkCrash({required String reason}) =>
    RustLib.instance.api.crateFfiTelemetryTelemetryMarkCrash(reason: reason);

/// Export the entire ring as an encrypted dump envelope (Map<u8,...>).
Uint8List telemetryDumpEncrypted() =>
    RustLib.instance.api.crateFfiTelemetryTelemetryDumpEncrypted();

/// JSON info: {"capacity_bytes","used_bytes","entries","sealed"}.
String telemetryInfoJson() =>
    RustLib.instance.api.crateFfiTelemetryTelemetryInfoJson();

bool telemetryIsSealed() =>
    RustLib.instance.api.crateFfiTelemetryTelemetryIsSealed();

/// Drops all events (key file stays).
void telemetryClear() => RustLib.instance.api.crateFfiTelemetryTelemetryClear();

/// JSON of recorded events: [[kind, ts_ms, payload], ...] (crash viewer).
String telemetryReadAllJson() =>
    RustLib.instance.api.crateFfiTelemetryTelemetryReadAllJson();
