// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Configure Turso database URL and auth bearer token for replication.
String dbTursoConfigure({required String url, required String authToken}) =>
    RustLib.instance.api
        .crateFfiTursoDbTursoConfigure(url: url, authToken: authToken);

/// Manually trigger database synchronization with the remote Turso Cloud database.
String dbTursoSync() => RustLib.instance.api.crateFfiTursoDbTursoSync();

/// Retrieve current Turso database replication sync status as a JSON string.
String dbTursoStatus() => RustLib.instance.api.crateFfiTursoDbTursoStatus();
