// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `tcp_probe`
// These functions are ignored because they have generic arguments: `json_ok`

/// SHA256 hash of input string (hex).
String utilSha256Hex({required String input}) =>
    RustLib.instance.api.crateFfiUtilUtilSha256Hex(input: input);

/// Base64URL (no padding) encode.
String utilBase64UrlEncode({required String input}) =>
    RustLib.instance.api.crateFfiUtilUtilBase64UrlEncode(input: input);

/// Base64URL (no padding) decode; returns the decoded string if valid UTF-8.
String utilBase64UrlDecode({required String input}) =>
    RustLib.instance.api.crateFfiUtilUtilBase64UrlDecode(input: input);

/// Truncate string to max length (char-boundary safe).
String utilTruncate({required String input, required BigInt maxLen}) =>
    RustLib.instance.api.crateFfiUtilUtilTruncate(input: input, maxLen: maxLen);

/// Extract hashtags (without `#`) from text.
List<String> utilExtractHashtags({required String text}) =>
    RustLib.instance.api.crateFfiUtilUtilExtractHashtags(text: text);

/// Apply thread affinity governing (pin calling thread to Performance or Efficiency cores).
bool utilApplyThreadAffinity({required bool targetPerformance}) => RustLib
    .instance.api
    .crateFfiUtilUtilApplyThreadAffinity(targetPerformance: targetPerformance);
