// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Publish a vouch (kind 31989) for `target_pubkey`. Returns the event id.
Future<String> vouchPublish(
        {required String targetPubkey, required String content}) =>
    RustLib.instance.api.crateFfiVouchVouchPublish(
        targetPubkey: targetPubkey, content: content);

/// Fetch vouches (kind 31989) addressed to `target_pubkey`. Only verified
/// signatures are returned. Returns JSON array of relation entries.
Future<String> vouchFetch({required String targetPubkey}) =>
    RustLib.instance.api.crateFfiVouchVouchFetch(targetPubkey: targetPubkey);
