// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IceConfig`, `IceServer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Get ICE configuration based on privacy settings.
/// `privacy_level`: "public" (all), "friends" (relay only).
String webrtcGetIceConfig({required String privacyLevel}) =>
    RustLib.instance.api
        .crateFfiWebrtcWebrtcGetIceConfig(privacyLevel: privacyLevel);

/// Get STUN servers
List<String> webrtcGetStunServers() =>
    RustLib.instance.api.crateFfiWebrtcWebrtcGetStunServers();

/// Get TURN servers (if enabled)
String webrtcGetTurnServers({String? authToken}) => RustLib.instance.api
    .crateFfiWebrtcWebrtcGetTurnServers(authToken: authToken);

/// Sanitize SDP to remove private IPs. `force_relay` true drops non-relay
/// candidates (matches `friends`/`private` privacy levels).
String webrtcSanitizeSdp({required String sdp, required bool forceRelay}) =>
    RustLib.instance.api
        .crateFfiWebrtcWebrtcSanitizeSdp(sdp: sdp, forceRelay: forceRelay);

/// Create peer connection config
String webrtcCreatePeerConfig({required String privacyLevel}) =>
    RustLib.instance.api
        .crateFfiWebrtcWebrtcCreatePeerConfig(privacyLevel: privacyLevel);

/// Extract candidates from SDP
List<String> webrtcExtractCandidates({required String sdp}) =>
    RustLib.instance.api.crateFfiWebrtcWebrtcExtractCandidates(sdp: sdp);

/// Add candidate to SDP
String webrtcAddCandidateToSdp(
        {required String sdp, required String candidate}) =>
    RustLib.instance.api
        .crateFfiWebrtcWebrtcAddCandidateToSdp(sdp: sdp, candidate: candidate);

/// Validate SDP
bool webrtcValidateSdp({required String sdp}) =>
    RustLib.instance.api.crateFfiWebrtcWebrtcValidateSdp(sdp: sdp);
