// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `InvoiceInfo`, `LnurlMetadata`, `NwcConnectionInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Parse a lud16 address into its parts (Rust-side URL hygiene).
Future<String> zapParseLnurlMetadata({required String lnurl}) =>
    RustLib.instance.api.crateFfiZapZapParseLnurlMetadata(lnurl: lnurl);

/// Connect to a Nostr Wallet Connect service. The NWC URI (which contains a
/// secret) is stored Rust-side only; `zap_get_nwc_status` never reveals it.
Future<bool> zapConnectNwc({required String nwcUri}) =>
    RustLib.instance.api.crateFfiZapZapConnectNwc(nwcUri: nwcUri);

/// Disconnect from NWC.
Future<bool> zapDisconnectNwc() =>
    RustLib.instance.api.crateFfiZapZapDisconnectNwc();

/// Get NWC connection status (never includes the secret).
Future<String> zapGetNwcStatus() =>
    RustLib.instance.api.crateFfiZapZapGetNwcStatus();

/// Get connected NWC pubkey (for display), or error if disconnected.
Future<String> zapGetNwcPubkey() =>
    RustLib.instance.api.crateFfiZapZapGetNwcPubkey();

/// Fetch invoice for zap via the connected NWC provider (kind 4 request is
/// built Rust-side; the response relay listener stores the invoice row).
Future<String> zapFetchInvoice(
        {required String lnurl,
        required BigInt amountMsat,
        required String comment,
        required String nostrEvent}) =>
    RustLib.instance.api.crateFfiZapZapFetchInvoice(
        lnurl: lnurl,
        amountMsat: amountMsat,
        comment: comment,
        nostrEvent: nostrEvent);

/// Get total zap amounts for an event from the local DB (invoice amounts
/// only — never the `amount` tag of an unverified receipt).
Future<BigInt> zapGetTotalMsat({required String eventId}) =>
    RustLib.instance.api.crateFfiZapZapGetTotalMsat(eventId: eventId);

/// Fetch stored zap receipt rows for an event as raw JSON.
Future<String> zapFetchReceipts(
        {required String eventId, required int limit}) =>
    RustLib.instance.api
        .crateFfiZapZapFetchReceipts(eventId: eventId, limit: limit);
