// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Verify a Zero-Knowledge STARK state rollup proof for feed threads
String zkVerifyRollup({required String rollupJson}) =>
    RustLib.instance.api.crateFfiZkZkVerifyRollup(rollupJson: rollupJson);

/// Apply a verified ZK state rollup directly to the database cache
bool zkApplyRollup({required String dbPath, required String rollupJson}) =>
    RustLib.instance.api
        .crateFfiZkZkApplyRollup(dbPath: dbPath, rollupJson: rollupJson);
