[package]
name = "soshal-analytics-core"
version = { workspace = true }
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
soshal-nostr-core = { path = "../nostr-core" }
streaming_algorithms = { workspace = true }
ulid = { workspace = true }


[lints]
workspace = true
