[package]
name = "soshal-relay-core"
version = { workspace = true }
edition = "2021"

[dependencies]
nostr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
soshal-common-core = { path = "../common-core" }
soshal-network-core = { path = "../network-core" }
tokio = { workspace = true }
rayon = { workspace = true }

[lints]
workspace = true